// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import gocent "github.com/centrifugal/gocent"

import mock "github.com/stretchr/testify/mock"

// CentrifugoInterface is an autogenerated mock type for the CentrifugoInterface type
type CentrifugoInterface struct {
	mock.Mock
}

// Info provides a mock function with given fields: ctx
func (_m *CentrifugoInterface) Info(ctx context.Context) (gocent.InfoResult, error) {
	ret := _m.Called(ctx)

	var r0 gocent.InfoResult
	if rf, ok := ret.Get(0).(func(context.Context) gocent.InfoResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(gocent.InfoResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publish provides a mock function with given fields: _a0, _a1
func (_m *CentrifugoInterface) Publish(_a0 string, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
