// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	proto "github.com/paysuper/paysuper-reporter/pkg/proto"
	mock "github.com/stretchr/testify/mock"
)

// DocumentGeneratorInterface is an autogenerated mock type for the DocumentGeneratorInterface type
type DocumentGeneratorInterface struct {
	mock.Mock
}

// Render provides a mock function with given fields: payload
func (_m *DocumentGeneratorInterface) Render(payload *proto.GeneratorPayload) ([]byte, error) {
	ret := _m.Called(payload)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*proto.GeneratorPayload) []byte); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*proto.GeneratorPayload) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
