// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateFileRequest struct {
	// @inject_tag: query:"merchant_id" validate:"required,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" query:"merchant_id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: query:"period_from" validate:"required,numeric,gt=0"
	PeriodFrom int64 `protobuf:"varint,2,opt,name=period_from,json=periodFrom,proto3" json:"period_from,omitempty" query:"period_from" validate:"required,numeric,gt=0"`
	// @inject_tag: query:"period_to" validate:"required,numeric,gt=0"
	PeriodTo int64 `protobuf:"varint,3,opt,name=period_to,json=periodTo,proto3" json:"period_to,omitempty" query:"period_to" validate:"required,numeric,gt=0"`
	// @inject_tag: query:"report_type" validate:"required,alpha"
	ReportType string `protobuf:"bytes,4,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty" query:"report_type" validate:"required,alpha"`
	// @inject_tag: query:"file_type" validate:"required,alpha"
	FileType             string   `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty" query:"file_type" validate:"required,alpha"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CreateFileRequest) Reset()         { *m = CreateFileRequest{} }
func (m *CreateFileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileRequest) ProtoMessage()    {}
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *CreateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileRequest.Unmarshal(m, b)
}
func (m *CreateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileRequest.Marshal(b, m, deterministic)
}
func (m *CreateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileRequest.Merge(m, src)
}
func (m *CreateFileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileRequest.Size(m)
}
func (m *CreateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileRequest proto.InternalMessageInfo

func (m *CreateFileRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CreateFileRequest) GetPeriodFrom() int64 {
	if m != nil {
		return m.PeriodFrom
	}
	return 0
}

func (m *CreateFileRequest) GetPeriodTo() int64 {
	if m != nil {
		return m.PeriodTo
	}
	return 0
}

func (m *CreateFileRequest) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *CreateFileRequest) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

type ResponseError struct {
	//@inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	//@inject_tag: json:"message"
	Message              *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte                `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                 `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ResponseError) Reset()         { *m = ResponseError{} }
func (m *ResponseError) String() string { return proto.CompactTextString(m) }
func (*ResponseError) ProtoMessage()    {}
func (*ResponseError) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *ResponseError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseError.Unmarshal(m, b)
}
func (m *ResponseError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseError.Marshal(b, m, deterministic)
}
func (m *ResponseError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseError.Merge(m, src)
}
func (m *ResponseError) XXX_Size() int {
	return xxx_messageInfo_ResponseError.Size(m)
}
func (m *ResponseError) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseError.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseError proto.InternalMessageInfo

func (m *ResponseError) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseError) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type ResponseErrorMessage struct {
	//@inject_tag: json:"code"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	//@inject_tag: json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	//@inject_tag: json:"details,omitempty"
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ResponseErrorMessage) Reset()         { *m = ResponseErrorMessage{} }
func (m *ResponseErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseErrorMessage) ProtoMessage()    {}
func (*ResponseErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *ResponseErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseErrorMessage.Unmarshal(m, b)
}
func (m *ResponseErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseErrorMessage.Marshal(b, m, deterministic)
}
func (m *ResponseErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseErrorMessage.Merge(m, src)
}
func (m *ResponseErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseErrorMessage.Size(m)
}
func (m *ResponseErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseErrorMessage proto.InternalMessageInfo

func (m *ResponseErrorMessage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResponseErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseErrorMessage) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type CreateFileResponse struct {
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"message,omitempty"
	Message *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// @inject_tag: json:"file_id"
	FileId               string   `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CreateFileResponse) Reset()         { *m = CreateFileResponse{} }
func (m *CreateFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileResponse) ProtoMessage()    {}
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *CreateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileResponse.Unmarshal(m, b)
}
func (m *CreateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileResponse.Merge(m, src)
}
func (m *CreateFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileResponse.Size(m)
}
func (m *CreateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileResponse proto.InternalMessageInfo

func (m *CreateFileResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateFileResponse) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *CreateFileResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type UpdateFileRequest struct {
	// @inject_tag: query:"id" validate:"required,hexadecimal,len=24"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" query:"id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: query:"file_path" validate:"required"
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty" query:"file_path" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *UpdateFileRequest) Reset()         { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()    {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *UpdateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileRequest.Unmarshal(m, b)
}
func (m *UpdateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileRequest.Merge(m, src)
}
func (m *UpdateFileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileRequest.Size(m)
}
func (m *UpdateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileRequest proto.InternalMessageInfo

func (m *UpdateFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateFileRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type GetFileRequest struct {
	// @inject_tag: query:"merchant_id" validate:"required,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" query:"merchant_id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: query:"id" validate:"required,hexadecimal,len=24"
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" query:"id" validate:"required,hexadecimal,len=24"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (m *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(m, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *GetFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFileResponse struct {
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"message,omitempty"
	Message *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// @inject_tag: json:"file"
	File                 *ReportFile `protobuf:"bytes,3,opt,name=file,proto3" json:"file"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (m *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(m, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetFileResponse) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *GetFileResponse) GetFile() *ReportFile {
	if m != nil {
		return m.File
	}
	return nil
}

type ReportFile struct {
	//@inject_tag: json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// @inject_tag: json:"merchant_id"
	MerchantId string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id"`
	// @inject_tag: json:"file_path"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"file_path"`
	//@inject_tag: json:"date_from"
	DateFrom *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3" json:"date_from"`
	//@inject_tag: json:"date_to"
	DateTo *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3" json:"date_to"`
	// @inject_tag: json:"created_at"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ReportFile) Reset()         { *m = ReportFile{} }
func (m *ReportFile) String() string { return proto.CompactTextString(m) }
func (*ReportFile) ProtoMessage()    {}
func (*ReportFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{7}
}

func (m *ReportFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportFile.Unmarshal(m, b)
}
func (m *ReportFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportFile.Marshal(b, m, deterministic)
}
func (m *ReportFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportFile.Merge(m, src)
}
func (m *ReportFile) XXX_Size() int {
	return xxx_messageInfo_ReportFile.Size(m)
}
func (m *ReportFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportFile.DiscardUnknown(m)
}

var xxx_messageInfo_ReportFile proto.InternalMessageInfo

func (m *ReportFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReportFile) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ReportFile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ReportFile) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *ReportFile) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

func (m *ReportFile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DeleteOldestReportFilesRequest struct {
	// @inject_tag: query:"days" validate:"required,number"
	Days                 int32    `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty" query:"days" validate:"required,number"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *DeleteOldestReportFilesRequest) Reset()         { *m = DeleteOldestReportFilesRequest{} }
func (m *DeleteOldestReportFilesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOldestReportFilesRequest) ProtoMessage()    {}
func (*DeleteOldestReportFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{8}
}

func (m *DeleteOldestReportFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOldestReportFilesRequest.Unmarshal(m, b)
}
func (m *DeleteOldestReportFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOldestReportFilesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOldestReportFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOldestReportFilesRequest.Merge(m, src)
}
func (m *DeleteOldestReportFilesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOldestReportFilesRequest.Size(m)
}
func (m *DeleteOldestReportFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOldestReportFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOldestReportFilesRequest proto.InternalMessageInfo

func (m *DeleteOldestReportFilesRequest) GetDays() int32 {
	if m != nil {
		return m.Days
	}
	return 0
}

type ReportRequest struct {
	//@inject_tag: json:"file_id" validate:"required,hexadecimal,len=24"
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id" validate:"required,hexadecimal,len=24"`
	//@inject_tag: json:"template_id" validate:"required,alpha"
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id" validate:"required,alpha"`
	//@inject_tag: json:"template_id" validate:"required,alpha"
	OutputFormat string `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"template_id" validate:"required,alpha"`
	//@inject_tag: json:"table_name" validate:"required,alpha"
	TableName string `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name" validate:"required,alpha"`
	//@inject_tag: json:"fields" validate:"required,dive,alpha"
	Fields []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields" validate:"required,dive,alpha"`
	//@inject_tag: json:"match" validate:"required"
	Match []byte `protobuf:"bytes,6,opt,name=match,proto3" json:"match" validate:"required"`
	//@inject_tag: json:"group"
	Group                []byte   `protobuf:"bytes,7,opt,name=group,proto3" json:"group"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{9}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *ReportRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ReportRequest) GetOutputFormat() string {
	if m != nil {
		return m.OutputFormat
	}
	return ""
}

func (m *ReportRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ReportRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ReportRequest) GetMatch() []byte {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *ReportRequest) GetGroup() []byte {
	if m != nil {
		return m.Group
	}
	return nil
}

type Payload struct {
	//@inject_tag: json:"template"
	Template *PayloadTemplate `protobuf:"bytes,1,opt,name=template,proto3" json:"template"`
	//@inject_tag: json:"options"
	Options *PayloadOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options"`
	//@inject_tag: json:"data"
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{10}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTemplate() *PayloadTemplate {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Payload) GetOptions() *PayloadOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PayloadTemplate struct {
	//@inject_tag: json:"shortid,omitempty"
	ShortId string `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"shortid,omitempty"`
	//@inject_tag: json:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//@inject_tag: json:"recipe,omitempty"
	Recipe string `protobuf:"bytes,3,opt,name=recipe,proto3" json:"recipe,omitempty"`
	//@inject_tag: json:"content,omitempty"
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PayloadTemplate) Reset()         { *m = PayloadTemplate{} }
func (m *PayloadTemplate) String() string { return proto.CompactTextString(m) }
func (*PayloadTemplate) ProtoMessage()    {}
func (*PayloadTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{11}
}

func (m *PayloadTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadTemplate.Unmarshal(m, b)
}
func (m *PayloadTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadTemplate.Marshal(b, m, deterministic)
}
func (m *PayloadTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadTemplate.Merge(m, src)
}
func (m *PayloadTemplate) XXX_Size() int {
	return xxx_messageInfo_PayloadTemplate.Size(m)
}
func (m *PayloadTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadTemplate proto.InternalMessageInfo

func (m *PayloadTemplate) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

func (m *PayloadTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayloadTemplate) GetRecipe() string {
	if m != nil {
		return m.Recipe
	}
	return ""
}

func (m *PayloadTemplate) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PayloadOptions struct {
	//@inject_tag: json:"timeout,omitempty"
	Timeout              string   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PayloadOptions) Reset()         { *m = PayloadOptions{} }
func (m *PayloadOptions) String() string { return proto.CompactTextString(m) }
func (*PayloadOptions) ProtoMessage()    {}
func (*PayloadOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{12}
}

func (m *PayloadOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadOptions.Unmarshal(m, b)
}
func (m *PayloadOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadOptions.Marshal(b, m, deterministic)
}
func (m *PayloadOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadOptions.Merge(m, src)
}
func (m *PayloadOptions) XXX_Size() int {
	return xxx_messageInfo_PayloadOptions.Size(m)
}
func (m *PayloadOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadOptions proto.InternalMessageInfo

func (m *PayloadOptions) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type LoadFileResponse struct {
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"message,omitempty"
	Message *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	//@inject_tag: json:"file"
	File *File `protobuf:"bytes,3,opt,name=file,proto3" json:"file"`
	//@inject_tag: json:"content_type"
	ContentType          string   `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *LoadFileResponse) Reset()         { *m = LoadFileResponse{} }
func (m *LoadFileResponse) String() string { return proto.CompactTextString(m) }
func (*LoadFileResponse) ProtoMessage()    {}
func (*LoadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{13}
}

func (m *LoadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadFileResponse.Unmarshal(m, b)
}
func (m *LoadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadFileResponse.Marshal(b, m, deterministic)
}
func (m *LoadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadFileResponse.Merge(m, src)
}
func (m *LoadFileResponse) XXX_Size() int {
	return xxx_messageInfo_LoadFileResponse.Size(m)
}
func (m *LoadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadFileResponse proto.InternalMessageInfo

func (m *LoadFileResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoadFileResponse) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *LoadFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *LoadFileResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type File struct {
	//@inject_tag: json:"file,omitempty"
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{14}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateFileRequest)(nil), "proto.CreateFileRequest")
	proto.RegisterType((*ResponseError)(nil), "proto.ResponseError")
	proto.RegisterType((*ResponseErrorMessage)(nil), "proto.ResponseErrorMessage")
	proto.RegisterType((*CreateFileResponse)(nil), "proto.CreateFileResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "proto.UpdateFileRequest")
	proto.RegisterType((*GetFileRequest)(nil), "proto.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "proto.GetFileResponse")
	proto.RegisterType((*ReportFile)(nil), "proto.ReportFile")
	proto.RegisterType((*DeleteOldestReportFilesRequest)(nil), "proto.DeleteOldestReportFilesRequest")
	proto.RegisterType((*ReportRequest)(nil), "proto.ReportRequest")
	proto.RegisterType((*Payload)(nil), "proto.Payload")
	proto.RegisterType((*PayloadTemplate)(nil), "proto.PayloadTemplate")
	proto.RegisterType((*PayloadOptions)(nil), "proto.PayloadOptions")
	proto.RegisterType((*LoadFileResponse)(nil), "proto.LoadFileResponse")
	proto.RegisterType((*File)(nil), "proto.File")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5f, 0x6f, 0x23, 0x35,
	0x10, 0xef, 0xa6, 0xf9, 0x3b, 0xe9, 0xb5, 0xd4, 0x2a, 0xbd, 0xbd, 0x9c, 0xa0, 0xc5, 0x08, 0xe9,
	0x84, 0x44, 0x22, 0x72, 0x20, 0x04, 0x42, 0x88, 0xe3, 0xa0, 0xa8, 0x12, 0x70, 0xa7, 0x25, 0xbc,
	0xf0, 0x70, 0x91, 0x9b, 0x9d, 0x24, 0x2b, 0x76, 0x63, 0xe3, 0xf5, 0x22, 0x45, 0xe2, 0x89, 0x17,
	0x5e, 0xf9, 0x12, 0xbc, 0xf3, 0x55, 0xf8, 0x3a, 0x3c, 0x21, 0x8f, 0xed, 0x4d, 0x93, 0x16, 0x10,
	0xd2, 0xf5, 0x25, 0xeb, 0xf9, 0xcd, 0x8c, 0xc7, 0xf3, 0xf3, 0xcc, 0x38, 0xd0, 0x57, 0x5a, 0x1a,
	0x39, 0xa4, 0x5f, 0xd6, 0xa2, 0xcf, 0xe0, 0x6c, 0x21, 0xe5, 0x22, 0xc7, 0x11, 0x49, 0x57, 0xd5,
	0x7c, 0x64, 0xb2, 0x02, 0x4b, 0x23, 0x0a, 0xe5, 0xec, 0xf8, 0x1f, 0x11, 0x1c, 0x3f, 0xd5, 0x28,
	0x0c, 0x5e, 0x64, 0x39, 0x26, 0xf8, 0x63, 0x85, 0xa5, 0x61, 0x67, 0xd0, 0x2f, 0x50, 0xcf, 0x96,
	0x62, 0x65, 0xa6, 0x59, 0x1a, 0x47, 0xe7, 0xd1, 0xa3, 0x5e, 0x02, 0x01, 0xba, 0x4c, 0xad, 0x81,
	0x42, 0x9d, 0xc9, 0x74, 0x3a, 0xd7, 0xb2, 0x88, 0x1b, 0xe7, 0xd1, 0xa3, 0xfd, 0x04, 0x1c, 0x74,
	0xa1, 0x65, 0xc1, 0x1e, 0x42, 0xcf, 0x1b, 0x18, 0x19, 0xef, 0x93, 0xba, 0xeb, 0x80, 0x89, 0xb4,
	0xde, 0x1a, 0x95, 0xd4, 0x66, 0x6a, 0xd6, 0x0a, 0xe3, 0xa6, 0xdb, 0xde, 0x41, 0x93, 0xb5, 0x42,
	0xeb, 0x3d, 0xcf, 0x72, 0x74, 0xea, 0x16, 0xa9, 0xbb, 0x16, 0xb0, 0x4a, 0xfe, 0x02, 0xee, 0x25,
	0x58, 0x2a, 0xb9, 0x2a, 0xf1, 0x0b, 0xad, 0xa5, 0x66, 0xa7, 0xd0, 0x2e, 0x8d, 0x30, 0x55, 0x49,
	0x07, 0x6d, 0x25, 0x5e, 0x62, 0xef, 0x43, 0xa7, 0xc0, 0xb2, 0x14, 0x0b, 0xa4, 0x03, 0xf6, 0xc7,
	0x0f, 0x5d, 0xd2, 0xc3, 0x2d, 0xf7, 0xaf, 0x9d, 0x49, 0x12, 0x6c, 0xf9, 0x0b, 0x38, 0xb9, 0xcd,
	0x80, 0x31, 0x68, 0xce, 0x64, 0x8a, 0x9e, 0x0d, 0x5a, 0xb3, 0x78, 0x3b, 0x44, 0xaf, 0xde, 0xc5,
	0x6a, 0x52, 0x34, 0x22, 0xcb, 0x4b, 0x4a, 0xbf, 0x97, 0x04, 0x91, 0xff, 0x0c, 0xec, 0x3a, 0xe3,
	0x2e, 0xd2, 0x4b, 0x4e, 0x82, 0xdd, 0x87, 0x0e, 0x31, 0x98, 0xa5, 0x3e, 0x7c, 0xdb, 0x8a, 0x97,
	0x29, 0xff, 0x14, 0x8e, 0xbf, 0x53, 0xe9, 0xce, 0x7d, 0x1f, 0x42, 0xa3, 0xbe, 0xe6, 0x46, 0x96,
	0xd6, 0xfc, 0x2b, 0x61, 0x96, 0x3e, 0x31, 0xe2, 0xff, 0xb9, 0x30, 0x4b, 0xfe, 0x04, 0x0e, 0xbf,
	0x44, 0xf3, 0xbf, 0xca, 0xc5, 0xed, 0xdf, 0x08, 0xfb, 0xf3, 0x5f, 0x23, 0x38, 0xaa, 0xf7, 0xb8,
	0x1b, 0x02, 0xde, 0x82, 0xa6, 0x3d, 0x31, 0x65, 0xdf, 0x1f, 0x1f, 0xd7, 0x3e, 0xb6, 0xc6, 0x28,
	0x2e, 0xa9, 0xf9, 0x5f, 0x11, 0xc0, 0x06, 0xbc, 0x41, 0xc4, 0x4e, 0x66, 0x8d, 0x1b, 0x99, 0x31,
	0x68, 0x52, 0x91, 0x3a, 0x92, 0x69, 0xcd, 0x3e, 0x80, 0x9e, 0x25, 0xd8, 0xb5, 0x46, 0x93, 0xe2,
	0x0f, 0x86, 0xae, 0x11, 0x87, 0xa1, 0x11, 0x87, 0x93, 0xd0, 0x88, 0x49, 0x97, 0x6e, 0xc3, 0x36,
	0xcd, 0x63, 0xe8, 0x90, 0xa3, 0x91, 0x54, 0xf4, 0xff, 0xee, 0xd6, 0xb6, 0xa6, 0x13, 0xc9, 0x3e,
	0x04, 0x98, 0x51, 0x39, 0xa5, 0x53, 0x61, 0xe2, 0xf6, 0x7f, 0xfa, 0xf5, 0xbc, 0xf5, 0x13, 0xc3,
	0xdf, 0x83, 0xd7, 0x3f, 0xc7, 0x1c, 0x0d, 0x3e, 0xcb, 0x53, 0x2c, 0xcd, 0x86, 0x87, 0x32, 0xdc,
	0x2c, 0x83, 0x66, 0x2a, 0xd6, 0xe1, 0x4a, 0x68, 0xcd, 0xff, 0x8c, 0x6c, 0x03, 0x5a, 0xd3, 0x60,
	0x75, 0xad, 0xd8, 0xa2, 0xeb, 0xc5, 0x66, 0xe9, 0x33, 0x58, 0xa8, 0xdc, 0x26, 0xb5, 0xa1, 0x2f,
	0x40, 0x97, 0x29, 0x7b, 0x13, 0xee, 0xc9, 0xca, 0xa8, 0xca, 0x4c, 0xe7, 0x52, 0x17, 0xc2, 0x78,
	0x1e, 0x0f, 0x1c, 0x78, 0x41, 0x18, 0x7b, 0x0d, 0xc0, 0x88, 0xab, 0x1c, 0xa7, 0x2b, 0x51, 0x84,
	0x69, 0xd1, 0x23, 0xe4, 0x1b, 0x51, 0x50, 0xe1, 0xcc, 0x33, 0xcc, 0xd3, 0x32, 0x6e, 0x9d, 0xef,
	0xbb, 0xe0, 0x56, 0x62, 0x27, 0xd0, 0x2a, 0x84, 0x99, 0x2d, 0x89, 0x93, 0x83, 0xc4, 0x09, 0x16,
	0x5d, 0x68, 0x59, 0xa9, 0xb8, 0xe3, 0x50, 0x12, 0xf8, 0x2f, 0x11, 0x74, 0x9e, 0x8b, 0x75, 0x2e,
	0x45, 0xca, 0xc6, 0xd0, 0x0d, 0x27, 0xa4, 0x74, 0xfa, 0xe3, 0x53, 0x5f, 0x3d, 0xde, 0x62, 0xe2,
	0xb5, 0x49, 0x6d, 0xc7, 0x46, 0xd0, 0x91, 0xca, 0x64, 0x72, 0x55, 0xfa, 0x22, 0x7d, 0x75, 0xdb,
	0xe5, 0x99, 0x53, 0x26, 0xc1, 0xca, 0x11, 0x6b, 0x04, 0xe5, 0x7b, 0x90, 0xd0, 0x9a, 0x6b, 0x38,
	0xda, 0x89, 0xc0, 0x1e, 0x40, 0xb7, 0x5c, 0xda, 0x41, 0x59, 0x53, 0xdb, 0x21, 0xd9, 0x55, 0x1e,
	0xf1, 0xe1, 0x48, 0xa5, 0xb5, 0xa5, 0x42, 0xe3, 0x2c, 0xab, 0xeb, 0xd1, 0x4b, 0x76, 0x18, 0xcd,
	0xe4, 0xca, 0xe0, 0xca, 0x78, 0xfa, 0x82, 0xc8, 0xdf, 0x86, 0xc3, 0xed, 0x23, 0x5a, 0x5b, 0xfb,
	0x48, 0xc8, 0xca, 0x84, 0x88, 0x5e, 0xe4, 0xbf, 0x47, 0xf0, 0xca, 0x57, 0x52, 0xa4, 0x77, 0xd9,
	0xb6, 0x67, 0x5b, 0x6d, 0xdb, 0xf7, 0x3e, 0x9b, 0x86, 0x65, 0x6f, 0xc0, 0x81, 0x3f, 0xfb, 0xf5,
	0xc7, 0xa3, 0xef, 0x31, 0x7a, 0x20, 0x06, 0xd0, 0xa4, 0x66, 0x66, 0x7e, 0xaf, 0xc8, 0x71, 0x6c,
	0xd7, 0xe3, 0xdf, 0x1a, 0x70, 0xe4, 0x8a, 0x17, 0xf5, 0xb7, 0xa8, 0x7f, 0xca, 0x66, 0xc8, 0x9e,
	0x02, 0x6c, 0x06, 0x32, 0x8b, 0x7d, 0xcc, 0x1b, 0xaf, 0xe2, 0xe0, 0xc1, 0x2d, 0x1a, 0x97, 0x0b,
	0xdf, 0x63, 0x9f, 0x00, 0x6c, 0xe6, 0x6a, 0xbd, 0xc9, 0x8d, 0x51, 0x3b, 0x38, 0xb9, 0x8d, 0x06,
	0xbe, 0xc7, 0x3e, 0x82, 0x8e, 0x9f, 0x88, 0x2c, 0xd4, 0xce, 0xf6, 0x94, 0x1d, 0x9c, 0xee, 0xc2,
	0x75, 0xec, 0x8f, 0xa1, 0x1b, 0xee, 0xe5, 0x9f, 0x9c, 0xef, 0x7b, 0x78, 0xf7, 0xfe, 0xf8, 0xde,
	0x67, 0xef, 0x7e, 0x3f, 0x5a, 0x64, 0x66, 0x59, 0x5d, 0x0d, 0x67, 0xb2, 0x18, 0x29, 0xb1, 0x2e,
	0x2b, 0x85, 0xba, 0x5e, 0xbc, 0xa3, 0x3d, 0x5d, 0x23, 0xf5, 0xc3, 0xc2, 0xff, 0x91, 0x68, 0xd3,
	0xe7, 0xf1, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x51, 0x55, 0xa7, 0x29, 0x73, 0x08, 0x00, 0x00,
}
