// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateFileResponse struct {
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"message,omitempty"
	Message *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// @inject_tag: json:"file_id"
	FileId               string   `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CreateFileResponse) Reset()         { *m = CreateFileResponse{} }
func (m *CreateFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileResponse) ProtoMessage()    {}
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *CreateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileResponse.Unmarshal(m, b)
}
func (m *CreateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileResponse.Merge(m, src)
}
func (m *CreateFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileResponse.Size(m)
}
func (m *CreateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileResponse proto.InternalMessageInfo

func (m *CreateFileResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateFileResponse) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *CreateFileResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type ResponseErrorMessage struct {
	//@inject_tag: json:"code"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	//@inject_tag: json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	//@inject_tag: json:"details,omitempty"
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ResponseErrorMessage) Reset()         { *m = ResponseErrorMessage{} }
func (m *ResponseErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseErrorMessage) ProtoMessage()    {}
func (*ResponseErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *ResponseErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseErrorMessage.Unmarshal(m, b)
}
func (m *ResponseErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseErrorMessage.Marshal(b, m, deterministic)
}
func (m *ResponseErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseErrorMessage.Merge(m, src)
}
func (m *ResponseErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseErrorMessage.Size(m)
}
func (m *ResponseErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseErrorMessage proto.InternalMessageInfo

func (m *ResponseErrorMessage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResponseErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseErrorMessage) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type ReportFile struct {
	//@inject_tag: json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// @inject_tag: json:"user_id" validate:"required,hexadecimal,len=24"
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: json:"merchant_id" validate:"required,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: json:"report_type" validate:"required,alpha"
	ReportType string `protobuf:"bytes,4,opt,name=report_type,json=reportType,proto3" json:"report_type" validate:"required,alpha"`
	// @inject_tag: json:"file_type" validate:"required,alpha"
	FileType string `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type" validate:"required,alpha"`
	// @inject_tag: json:"params"
	Params []byte `protobuf:"bytes,6,opt,name=params,proto3" json:"params"`
	// @inject_tag: json:"template" validate:"required,hexadecimal"
	Template string `protobuf:"bytes,7,opt,name=template,proto3" json:"template" validate:"required,hexadecimal"`
	// @inject_tag: json:"retention_time"
	RetentionTime int32 `protobuf:"varint,8,opt,name=retention_time,json=retentionTime,proto3" json:"retention_time"`
	// @inject_tag: json:"send_notification"
	SendNotification bool `protobuf:"varint,9,opt,name=send_notification,json=sendNotification,proto3" json:"send_notification"`
	// @inject_tag: json:"created_at"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ReportFile) Reset()         { *m = ReportFile{} }
func (m *ReportFile) String() string { return proto.CompactTextString(m) }
func (*ReportFile) ProtoMessage()    {}
func (*ReportFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *ReportFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportFile.Unmarshal(m, b)
}
func (m *ReportFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportFile.Marshal(b, m, deterministic)
}
func (m *ReportFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportFile.Merge(m, src)
}
func (m *ReportFile) XXX_Size() int {
	return xxx_messageInfo_ReportFile.Size(m)
}
func (m *ReportFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportFile.DiscardUnknown(m)
}

var xxx_messageInfo_ReportFile proto.InternalMessageInfo

func (m *ReportFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReportFile) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ReportFile) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ReportFile) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *ReportFile) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *ReportFile) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ReportFile) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *ReportFile) GetRetentionTime() int32 {
	if m != nil {
		return m.RetentionTime
	}
	return 0
}

func (m *ReportFile) GetSendNotification() bool {
	if m != nil {
		return m.SendNotification
	}
	return false
}

func (m *ReportFile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateFileResponse)(nil), "proto.CreateFileResponse")
	proto.RegisterType((*ResponseErrorMessage)(nil), "proto.ResponseErrorMessage")
	proto.RegisterType((*ReportFile)(nil), "proto.ReportFile")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x51, 0x8b, 0xd4, 0x3c,
	0x14, 0xfd, 0x3a, 0xdf, 0x4e, 0x67, 0x7a, 0x47, 0x57, 0x37, 0xc8, 0x1a, 0x67, 0x1f, 0xb6, 0x0c,
	0x08, 0x05, 0xb1, 0xc5, 0x15, 0x1f, 0x04, 0x5f, 0x54, 0x14, 0xf6, 0x41, 0x85, 0x3a, 0x4f, 0x3e,
	0x58, 0xb2, 0xed, 0x9d, 0x6e, 0xb0, 0x6d, 0x42, 0x72, 0x2b, 0x0c, 0xf8, 0x3f, 0xfd, 0x3b, 0xd2,
	0xa4, 0x9d, 0x51, 0xf4, 0xa5, 0xcd, 0x39, 0xf7, 0xe4, 0xe4, 0x26, 0xf7, 0xc0, 0x4a, 0x1b, 0x45,
	0x2a, 0x75, 0x5f, 0x36, 0x77, 0xbf, 0xf5, 0x65, 0xad, 0x54, 0xdd, 0x60, 0xe6, 0xd0, 0x4d, 0xbf,
	0xcb, 0x48, 0xb6, 0x68, 0x49, 0xb4, 0xda, 0xeb, 0x36, 0x3f, 0x80, 0xbd, 0x35, 0x28, 0x08, 0xdf,
	0xcb, 0x06, 0x73, 0xb4, 0x5a, 0x75, 0x16, 0xd9, 0x39, 0x84, 0x96, 0x04, 0xf5, 0x96, 0x07, 0x71,
	0x90, 0xcc, 0xf3, 0x11, 0xb1, 0x17, 0xb0, 0x68, 0xd1, 0x5a, 0x51, 0x23, 0x9f, 0xc5, 0x41, 0xb2,
	0xba, 0xba, 0xf0, 0x36, 0xe9, 0xb4, 0xf3, 0x9d, 0x31, 0xca, 0x7c, 0xf0, 0x92, 0x7c, 0xd2, 0xb2,
	0x87, 0xb0, 0xd8, 0xc9, 0x06, 0x0b, 0x59, 0xf1, 0xff, 0xe3, 0x20, 0x89, 0xf2, 0x70, 0x80, 0xd7,
	0xd5, 0xe6, 0x2b, 0x3c, 0xf8, 0xd7, 0x4e, 0xc6, 0xe0, 0xa4, 0x54, 0x15, 0xba, 0xd3, 0xa3, 0xdc,
	0xad, 0x19, 0xff, 0xf3, 0xec, 0xe8, 0x68, 0xcf, 0x61, 0x51, 0x21, 0x09, 0xd9, 0xd8, 0xd1, 0x7e,
	0x82, 0x9b, 0x9f, 0x33, 0x80, 0x1c, 0xb5, 0x32, 0x34, 0x5c, 0x8f, 0x9d, 0xc2, 0x4c, 0x56, 0xa3,
	0xe9, 0x4c, 0x56, 0x43, 0x5f, 0xbd, 0x45, 0x33, 0xf4, 0xe5, 0x2d, 0xc3, 0x01, 0x5e, 0x57, 0xec,
	0x12, 0x56, 0x2d, 0x9a, 0xf2, 0x56, 0x74, 0x74, 0x6c, 0x1a, 0x26, 0xca, 0x0b, 0x8c, 0xf3, 0x2d,
	0x68, 0xaf, 0x91, 0x9f, 0x78, 0x81, 0xa7, 0xb6, 0x7b, 0x8d, 0xec, 0x02, 0x22, 0x77, 0x65, 0x57,
	0x9e, 0xbb, 0xf2, 0x72, 0x20, 0x5c, 0xf1, 0x1c, 0x42, 0x2d, 0x8c, 0x68, 0x2d, 0x0f, 0xe3, 0x20,
	0xb9, 0x93, 0x8f, 0x88, 0xad, 0x61, 0x49, 0xd8, 0xea, 0x46, 0x10, 0xf2, 0x85, 0xdf, 0x33, 0x61,
	0xf6, 0x18, 0x4e, 0x0d, 0x12, 0x76, 0x24, 0x55, 0x57, 0x0c, 0x53, 0xe4, 0x4b, 0x37, 0x9a, 0xbb,
	0x07, 0x76, 0x2b, 0x5b, 0x64, 0x4f, 0xe0, 0xcc, 0x62, 0x57, 0x15, 0x9d, 0x22, 0xb9, 0x93, 0xa5,
	0x18, 0x0a, 0x3c, 0x8a, 0x83, 0x64, 0x99, 0xdf, 0x1f, 0x0a, 0x1f, 0x7f, 0xe3, 0xd9, 0x4b, 0x80,
	0xd2, 0x0d, 0xbf, 0x2a, 0x04, 0x71, 0x70, 0x13, 0x5d, 0xa7, 0x3e, 0x32, 0xe9, 0x14, 0x99, 0x74,
	0x3b, 0x45, 0x26, 0x8f, 0x46, 0xf5, 0x6b, 0xba, 0xfa, 0x04, 0xf7, 0xfc, 0xc3, 0xa2, 0xf9, 0x8c,
	0xe6, 0xbb, 0x2c, 0x91, 0xbd, 0x02, 0x38, 0x46, 0x89, 0x9d, 0x1d, 0x92, 0x31, 0x3d, 0xff, 0xfa,
	0xd1, 0x48, 0xfd, 0x1d, 0xb8, 0xcd, 0x7f, 0x6f, 0x9e, 0x7d, 0xc9, 0x6a, 0x49, 0xb7, 0xfd, 0x4d,
	0x5a, 0xaa, 0x36, 0xd3, 0x62, 0x6f, 0x7b, 0x8d, 0xe6, 0xb0, 0x78, 0x6a, 0xc6, 0xd3, 0x32, 0xfd,
	0xad, 0x1e, 0xe3, 0x1c, 0xba, 0xdf, 0xf3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x0d, 0x3c,
	0xa3, 0xf9, 0x02, 0x00, 0x00,
}
