// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateFileResponse struct {
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"message,omitempty"
	Message *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// @inject_tag: json:"file"
	File                 *ReportFile `protobuf:"bytes,3,opt,name=file,proto3" json:"file"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CreateFileResponse) Reset()         { *m = CreateFileResponse{} }
func (m *CreateFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileResponse) ProtoMessage()    {}
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *CreateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileResponse.Unmarshal(m, b)
}
func (m *CreateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileResponse.Merge(m, src)
}
func (m *CreateFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileResponse.Size(m)
}
func (m *CreateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileResponse proto.InternalMessageInfo

func (m *CreateFileResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateFileResponse) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *CreateFileResponse) GetFile() *ReportFile {
	if m != nil {
		return m.File
	}
	return nil
}

type LoadFileRequest struct {
	// @inject_tag: query:"merchant_id" validate:"required,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" query:"merchant_id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: query:"id" validate:"required,hexadecimal,len=24"
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" query:"id" validate:"required,hexadecimal,len=24"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *LoadFileRequest) Reset()         { *m = LoadFileRequest{} }
func (m *LoadFileRequest) String() string { return proto.CompactTextString(m) }
func (*LoadFileRequest) ProtoMessage()    {}
func (*LoadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *LoadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadFileRequest.Unmarshal(m, b)
}
func (m *LoadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadFileRequest.Marshal(b, m, deterministic)
}
func (m *LoadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadFileRequest.Merge(m, src)
}
func (m *LoadFileRequest) XXX_Size() int {
	return xxx_messageInfo_LoadFileRequest.Size(m)
}
func (m *LoadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadFileRequest proto.InternalMessageInfo

func (m *LoadFileRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *LoadFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type LoadFileResponse struct {
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"message,omitempty"
	Message *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	//@inject_tag: json:"file"
	File *File `protobuf:"bytes,3,opt,name=file,proto3" json:"file"`
	//@inject_tag: json:"content_type"
	ContentType          string   `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *LoadFileResponse) Reset()         { *m = LoadFileResponse{} }
func (m *LoadFileResponse) String() string { return proto.CompactTextString(m) }
func (*LoadFileResponse) ProtoMessage()    {}
func (*LoadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *LoadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadFileResponse.Unmarshal(m, b)
}
func (m *LoadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadFileResponse.Marshal(b, m, deterministic)
}
func (m *LoadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadFileResponse.Merge(m, src)
}
func (m *LoadFileResponse) XXX_Size() int {
	return xxx_messageInfo_LoadFileResponse.Size(m)
}
func (m *LoadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadFileResponse proto.InternalMessageInfo

func (m *LoadFileResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoadFileResponse) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *LoadFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *LoadFileResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type ResponseError struct {
	//@inject_tag: json:"status"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	//@inject_tag: json:"message"
	Message              *ResponseErrorMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte                `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                 `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ResponseError) Reset()         { *m = ResponseError{} }
func (m *ResponseError) String() string { return proto.CompactTextString(m) }
func (*ResponseError) ProtoMessage()    {}
func (*ResponseError) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *ResponseError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseError.Unmarshal(m, b)
}
func (m *ResponseError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseError.Marshal(b, m, deterministic)
}
func (m *ResponseError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseError.Merge(m, src)
}
func (m *ResponseError) XXX_Size() int {
	return xxx_messageInfo_ResponseError.Size(m)
}
func (m *ResponseError) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseError.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseError proto.InternalMessageInfo

func (m *ResponseError) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseError) GetMessage() *ResponseErrorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type ResponseErrorMessage struct {
	//@inject_tag: json:"code"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	//@inject_tag: json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	//@inject_tag: json:"details,omitempty"
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ResponseErrorMessage) Reset()         { *m = ResponseErrorMessage{} }
func (m *ResponseErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseErrorMessage) ProtoMessage()    {}
func (*ResponseErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *ResponseErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseErrorMessage.Unmarshal(m, b)
}
func (m *ResponseErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseErrorMessage.Marshal(b, m, deterministic)
}
func (m *ResponseErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseErrorMessage.Merge(m, src)
}
func (m *ResponseErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseErrorMessage.Size(m)
}
func (m *ResponseErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseErrorMessage proto.InternalMessageInfo

func (m *ResponseErrorMessage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResponseErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseErrorMessage) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type ReportFile struct {
	//@inject_tag: json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// @inject_tag: json:"merchant_id" validate:"required,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id" validate:"required,hexadecimal,len=24"`
	// @inject_tag: json:"report_type" validate:"required,alpha"
	ReportType string `protobuf:"bytes,3,opt,name=report_type,json=reportType,proto3" json:"report_type" validate:"required,alpha"`
	// @inject_tag: json:"file_type" validate:"required,alpha"
	FileType string `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type" validate:"required,alpha"`
	// @inject_tag: json:"params" structure:"params,jsonpb"
	Params []byte `protobuf:"bytes,5,opt,name=params,proto3" json:"params" structure:"params,jsonpb"`
	// @inject_tag: json:"template" validate:"required,hexadecimal"
	Template string `protobuf:"bytes,6,opt,name=template,proto3" json:"template" validate:"required,hexadecimal"`
	// @inject_tag: json:"created_at"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ReportFile) Reset()         { *m = ReportFile{} }
func (m *ReportFile) String() string { return proto.CompactTextString(m) }
func (*ReportFile) ProtoMessage()    {}
func (*ReportFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *ReportFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportFile.Unmarshal(m, b)
}
func (m *ReportFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportFile.Marshal(b, m, deterministic)
}
func (m *ReportFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportFile.Merge(m, src)
}
func (m *ReportFile) XXX_Size() int {
	return xxx_messageInfo_ReportFile.Size(m)
}
func (m *ReportFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportFile.DiscardUnknown(m)
}

var xxx_messageInfo_ReportFile proto.InternalMessageInfo

func (m *ReportFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReportFile) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ReportFile) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *ReportFile) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *ReportFile) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ReportFile) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *ReportFile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type File struct {
	//@inject_tag: json:"file,omitempty"
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type ReportRequest struct {
	//@inject_tag: json:"file_id" validate:"required,hexadecimal,len=24"
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id" validate:"required,hexadecimal,len=24"`
	//@inject_tag: json:"template_id" validate:"required,alpha"
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id" validate:"required,alpha"`
	//@inject_tag: json:"template_id" validate:"required,alpha"
	OutputFormat string `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"template_id" validate:"required,alpha"`
	//@inject_tag: json:"table_name" validate:"required,alpha"
	TableName string `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name" validate:"required,alpha"`
	//@inject_tag: json:"fields" validate:"required,dive,alpha"
	Fields []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields" validate:"required,dive,alpha"`
	//@inject_tag: json:"match" validate:"required"
	Match []byte `protobuf:"bytes,6,opt,name=match,proto3" json:"match" validate:"required"`
	//@inject_tag: json:"group"
	Group                []byte   `protobuf:"bytes,7,opt,name=group,proto3" json:"group"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{7}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *ReportRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ReportRequest) GetOutputFormat() string {
	if m != nil {
		return m.OutputFormat
	}
	return ""
}

func (m *ReportRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ReportRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ReportRequest) GetMatch() []byte {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *ReportRequest) GetGroup() []byte {
	if m != nil {
		return m.Group
	}
	return nil
}

type GeneratorPayload struct {
	//@inject_tag: json:"template"
	Template *GeneratorTemplate `protobuf:"bytes,1,opt,name=template,proto3" json:"template"`
	//@inject_tag: json:"options"
	Options *GeneratorOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options"`
	//@inject_tag: json:"data"
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GeneratorPayload) Reset()         { *m = GeneratorPayload{} }
func (m *GeneratorPayload) String() string { return proto.CompactTextString(m) }
func (*GeneratorPayload) ProtoMessage()    {}
func (*GeneratorPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{8}
}

func (m *GeneratorPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorPayload.Unmarshal(m, b)
}
func (m *GeneratorPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorPayload.Marshal(b, m, deterministic)
}
func (m *GeneratorPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorPayload.Merge(m, src)
}
func (m *GeneratorPayload) XXX_Size() int {
	return xxx_messageInfo_GeneratorPayload.Size(m)
}
func (m *GeneratorPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorPayload.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorPayload proto.InternalMessageInfo

func (m *GeneratorPayload) GetTemplate() *GeneratorTemplate {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *GeneratorPayload) GetOptions() *GeneratorOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *GeneratorPayload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GeneratorTemplate struct {
	//@inject_tag: json:"shortid,omitempty"
	ShortId string `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"shortid,omitempty"`
	//@inject_tag: json:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//@inject_tag: json:"recipe,omitempty"
	Recipe string `protobuf:"bytes,3,opt,name=recipe,proto3" json:"recipe,omitempty"`
	//@inject_tag: json:"content,omitempty"
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GeneratorTemplate) Reset()         { *m = GeneratorTemplate{} }
func (m *GeneratorTemplate) String() string { return proto.CompactTextString(m) }
func (*GeneratorTemplate) ProtoMessage()    {}
func (*GeneratorTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{9}
}

func (m *GeneratorTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorTemplate.Unmarshal(m, b)
}
func (m *GeneratorTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorTemplate.Marshal(b, m, deterministic)
}
func (m *GeneratorTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorTemplate.Merge(m, src)
}
func (m *GeneratorTemplate) XXX_Size() int {
	return xxx_messageInfo_GeneratorTemplate.Size(m)
}
func (m *GeneratorTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorTemplate proto.InternalMessageInfo

func (m *GeneratorTemplate) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

func (m *GeneratorTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GeneratorTemplate) GetRecipe() string {
	if m != nil {
		return m.Recipe
	}
	return ""
}

func (m *GeneratorTemplate) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GeneratorOptions struct {
	//@inject_tag: json:"timeout,omitempty"
	Timeout              string   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GeneratorOptions) Reset()         { *m = GeneratorOptions{} }
func (m *GeneratorOptions) String() string { return proto.CompactTextString(m) }
func (*GeneratorOptions) ProtoMessage()    {}
func (*GeneratorOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{10}
}

func (m *GeneratorOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorOptions.Unmarshal(m, b)
}
func (m *GeneratorOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorOptions.Marshal(b, m, deterministic)
}
func (m *GeneratorOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorOptions.Merge(m, src)
}
func (m *GeneratorOptions) XXX_Size() int {
	return xxx_messageInfo_GeneratorOptions.Size(m)
}
func (m *GeneratorOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorOptions proto.InternalMessageInfo

func (m *GeneratorOptions) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type RoyaltyReportDetails struct {
	//@inject_tag: bson:"gross_amount"
	GrossAmount float64 `protobuf:"fixed64,1,opt,name=gross_amount,json=grossAmount,proto3" json:"gross_amount,omitempty" bson:"gross_amount"`
	//@inject_tag: bson:"transactions_count"
	TransactionsCount int32 `protobuf:"varint,2,opt,name=transactions_count,json=transactionsCount,proto3" json:"transactions_count,omitempty" bson:"transactions_count"`
	//@inject_tag: bson:"fee_amount"
	FeeAmount float64 `protobuf:"fixed64,3,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty" bson:"fee_amount"`
	//@inject_tag: bson:"vat_amount"
	VatAmount float64 `protobuf:"fixed64,4,opt,name=vat_amount,json=vatAmount,proto3" json:"vat_amount,omitempty" bson:"vat_amount"`
	//@inject_tag: bson:"payout_amount"
	PayoutAmount float64 `protobuf:"fixed64,5,opt,name=payout_amount,json=payoutAmount,proto3" json:"payout_amount,omitempty" bson:"payout_amount"`
	//@inject_tag: bson:"currency"
	Currency             string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty" bson:"currency"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *RoyaltyReportDetails) Reset()         { *m = RoyaltyReportDetails{} }
func (m *RoyaltyReportDetails) String() string { return proto.CompactTextString(m) }
func (*RoyaltyReportDetails) ProtoMessage()    {}
func (*RoyaltyReportDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{11}
}

func (m *RoyaltyReportDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoyaltyReportDetails.Unmarshal(m, b)
}
func (m *RoyaltyReportDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoyaltyReportDetails.Marshal(b, m, deterministic)
}
func (m *RoyaltyReportDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoyaltyReportDetails.Merge(m, src)
}
func (m *RoyaltyReportDetails) XXX_Size() int {
	return xxx_messageInfo_RoyaltyReportDetails.Size(m)
}
func (m *RoyaltyReportDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RoyaltyReportDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RoyaltyReportDetails proto.InternalMessageInfo

func (m *RoyaltyReportDetails) GetGrossAmount() float64 {
	if m != nil {
		return m.GrossAmount
	}
	return 0
}

func (m *RoyaltyReportDetails) GetTransactionsCount() int32 {
	if m != nil {
		return m.TransactionsCount
	}
	return 0
}

func (m *RoyaltyReportDetails) GetFeeAmount() float64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

func (m *RoyaltyReportDetails) GetVatAmount() float64 {
	if m != nil {
		return m.VatAmount
	}
	return 0
}

func (m *RoyaltyReportDetails) GetPayoutAmount() float64 {
	if m != nil {
		return m.PayoutAmount
	}
	return 0
}

func (m *RoyaltyReportDetails) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type RoyaltyReportCorrection struct {
	// @inject_tag: validate:"omitempty,numeric,gt=0"
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty" validate:"omitempty,numeric,gt=0"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *RoyaltyReportCorrection) Reset()         { *m = RoyaltyReportCorrection{} }
func (m *RoyaltyReportCorrection) String() string { return proto.CompactTextString(m) }
func (*RoyaltyReportCorrection) ProtoMessage()    {}
func (*RoyaltyReportCorrection) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{12}
}

func (m *RoyaltyReportCorrection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoyaltyReportCorrection.Unmarshal(m, b)
}
func (m *RoyaltyReportCorrection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoyaltyReportCorrection.Marshal(b, m, deterministic)
}
func (m *RoyaltyReportCorrection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoyaltyReportCorrection.Merge(m, src)
}
func (m *RoyaltyReportCorrection) XXX_Size() int {
	return xxx_messageInfo_RoyaltyReportCorrection.Size(m)
}
func (m *RoyaltyReportCorrection) XXX_DiscardUnknown() {
	xxx_messageInfo_RoyaltyReportCorrection.DiscardUnknown(m)
}

var xxx_messageInfo_RoyaltyReportCorrection proto.InternalMessageInfo

func (m *RoyaltyReportCorrection) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RoyaltyReportCorrection) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type RoyaltyReport struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId           string                   `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CreatedAt            *timestamp.Timestamp     `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp     `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PayoutId             string                   `protobuf:"bytes,5,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	PayoutDate           *timestamp.Timestamp     `protobuf:"bytes,6,opt,name=payout_date,json=payoutDate,proto3" json:"payout_date,omitempty"`
	Status               string                   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PeriodFrom           *timestamp.Timestamp     `protobuf:"bytes,8,opt,name=period_from,json=periodFrom,proto3" json:"period_from,omitempty"`
	PeriodTo             *timestamp.Timestamp     `protobuf:"bytes,9,opt,name=period_to,json=periodTo,proto3" json:"period_to,omitempty"`
	AcceptExpireAt       *timestamp.Timestamp     `protobuf:"bytes,10,opt,name=accept_expire_at,json=acceptExpireAt,proto3" json:"accept_expire_at,omitempty"`
	AcceptedAt           *timestamp.Timestamp     `protobuf:"bytes,11,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	Amounts              *RoyaltyReportDetails    `protobuf:"bytes,12,opt,name=amounts,proto3" json:"amounts,omitempty"`
	Correction           *RoyaltyReportCorrection `protobuf:"bytes,13,opt,name=correction,proto3" json:"correction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte                   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *RoyaltyReport) Reset()         { *m = RoyaltyReport{} }
func (m *RoyaltyReport) String() string { return proto.CompactTextString(m) }
func (*RoyaltyReport) ProtoMessage()    {}
func (*RoyaltyReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{13}
}

func (m *RoyaltyReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoyaltyReport.Unmarshal(m, b)
}
func (m *RoyaltyReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoyaltyReport.Marshal(b, m, deterministic)
}
func (m *RoyaltyReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoyaltyReport.Merge(m, src)
}
func (m *RoyaltyReport) XXX_Size() int {
	return xxx_messageInfo_RoyaltyReport.Size(m)
}
func (m *RoyaltyReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RoyaltyReport.DiscardUnknown(m)
}

var xxx_messageInfo_RoyaltyReport proto.InternalMessageInfo

func (m *RoyaltyReport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoyaltyReport) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *RoyaltyReport) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RoyaltyReport) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RoyaltyReport) GetPayoutId() string {
	if m != nil {
		return m.PayoutId
	}
	return ""
}

func (m *RoyaltyReport) GetPayoutDate() *timestamp.Timestamp {
	if m != nil {
		return m.PayoutDate
	}
	return nil
}

func (m *RoyaltyReport) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RoyaltyReport) GetPeriodFrom() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodFrom
	}
	return nil
}

func (m *RoyaltyReport) GetPeriodTo() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodTo
	}
	return nil
}

func (m *RoyaltyReport) GetAcceptExpireAt() *timestamp.Timestamp {
	if m != nil {
		return m.AcceptExpireAt
	}
	return nil
}

func (m *RoyaltyReport) GetAcceptedAt() *timestamp.Timestamp {
	if m != nil {
		return m.AcceptedAt
	}
	return nil
}

func (m *RoyaltyReport) GetAmounts() *RoyaltyReportDetails {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *RoyaltyReport) GetCorrection() *RoyaltyReportCorrection {
	if m != nil {
		return m.Correction
	}
	return nil
}

type OrderViewPublic struct {
	// @inject_tag: json:"-" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"-" bson:"_id"`
	// @inject_tag: json:"uuid" bson:"uuid"
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid" bson:"uuid"`
	// @inject_tag: json:"total_payment_amount" bson:"total_payment_amount"
	TotalPaymentAmount float64 `protobuf:"fixed64,3,opt,name=total_payment_amount,json=totalPaymentAmount,proto3" json:"total_payment_amount" bson:"total_payment_amount"`
	// @inject_tag: json:"currency" bson:"currency"
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency" bson:"currency"`
	// @inject_tag: json:"project" bson:"project"
	Project *ProjectOrder `protobuf:"bytes,5,opt,name=project,proto3" json:"project" bson:"project"`
	// @inject_tag: bson:"created_at" bson:"created_at"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at" bson:"created_at"`
	// @inject_tag: json:"transaction" bson:"pm_order_id"
	Transaction string `protobuf:"bytes,7,opt,name=transaction,proto3" json:"transaction" bson:"pm_order_id"`
	// @inject_tag: json:"payment_method" bson:"payment_method"
	PaymentMethod *PaymentMethodOrder `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method" bson:"payment_method"`
	// @inject_tag: json:"country_code" bson:"country_code"
	CountryCode string `protobuf:"bytes,9,opt,name=country_code,json=countryCode,proto3" json:"country_code" bson:"country_code"`
	// @inject_tag: json:"merchant_id" bson:"merchant_id"
	MerchantId string `protobuf:"bytes,10,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id" bson:"merchant_id"`
	// @inject_tag: json:"locale" bson:"locale"
	Locale string `protobuf:"bytes,11,opt,name=locale,proto3" json:"locale" bson:"locale"`
	// @inject_tag: json:"status" bson:"status"
	Status string `protobuf:"bytes,12,opt,name=status,proto3" json:"status" bson:"status"`
	// @inject_tag: json:"transaction_date" bson:"pm_order_close_date"
	TransactionDate *timestamp.Timestamp `protobuf:"bytes,13,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date" bson:"pm_order_close_date"`
	// @inject_tag: json:"user" bson:"user"
	User *OrderUser `protobuf:"bytes,14,opt,name=user,proto3" json:"user" bson:"user"`
	// @inject_tag: json:"billing_address" bson:"billing_address"
	BillingAddress *OrderBillingAddress `protobuf:"bytes,15,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address" bson:"billing_address"`
	// @inject_tag: json:"type" bson:"type"
	Type string `protobuf:"bytes,16,opt,name=type,proto3" json:"type" bson:"type"`
	// @inject_tag: json:"is_vat_deduction" bson:"is_vat_deduction"
	IsVatDeduction bool `protobuf:"varint,17,opt,name=is_vat_deduction,json=isVatDeduction,proto3" json:"is_vat_deduction" bson:"is_vat_deduction"`
	// @inject_tag: json:"gross_revenue" bson:"gross_revenue"
	GrossRevenue *OrderViewMoney `protobuf:"bytes,18,opt,name=gross_revenue,json=grossRevenue,proto3" json:"gross_revenue" bson:"gross_revenue"`
	// @inject_tag: json:"tax_fee" bson:"tax_fee"
	TaxFee *OrderViewMoney `protobuf:"bytes,19,opt,name=tax_fee,json=taxFee,proto3" json:"tax_fee" bson:"tax_fee"`
	// @inject_tag: json:"tax_fee_currency_exchange_fee" bson:"tax_fee_currency_exchange_fee"
	TaxFeeCurrencyExchangeFee *OrderViewMoney `protobuf:"bytes,20,opt,name=tax_fee_currency_exchange_fee,json=taxFeeCurrencyExchangeFee,proto3" json:"tax_fee_currency_exchange_fee" bson:"tax_fee_currency_exchange_fee"`
	// @inject_tag: json:"tax_fee_total" bson:"tax_fee_total"
	TaxFeeTotal *OrderViewMoney `protobuf:"bytes,21,opt,name=tax_fee_total,json=taxFeeTotal,proto3" json:"tax_fee_total" bson:"tax_fee_total"`
	// @inject_tag: json:"method_fee_total" bson:"method_fee_total"
	MethodFeeTotal *OrderViewMoney `protobuf:"bytes,22,opt,name=method_fee_total,json=methodFeeTotal,proto3" json:"method_fee_total" bson:"method_fee_total"`
	// @inject_tag: json:"method_fee_tariff" bson:"method_fee_tariff"
	MethodFeeTariff *OrderViewMoney `protobuf:"bytes,23,opt,name=method_fee_tariff,json=methodFeeTariff,proto3" json:"method_fee_tariff" bson:"method_fee_tariff"`
	// @inject_tag: json:"method_fixed_fee_tariff" bson:"method_fixed_fee_tariff"
	MethodFixedFeeTariff *OrderViewMoney `protobuf:"bytes,24,opt,name=method_fixed_fee_tariff,json=methodFixedFeeTariff,proto3" json:"method_fixed_fee_tariff" bson:"method_fixed_fee_tariff"`
	// @inject_tag: json:"paysuper_fixed_fee" bson:"paysuper_fixed_fee"
	PaysuperFixedFee *OrderViewMoney `protobuf:"bytes,25,opt,name=paysuper_fixed_fee,json=paysuperFixedFee,proto3" json:"paysuper_fixed_fee" bson:"paysuper_fixed_fee"`
	// @inject_tag: json:"fees_total" bson:"fees_total"
	FeesTotal *OrderViewMoney `protobuf:"bytes,26,opt,name=fees_total,json=feesTotal,proto3" json:"fees_total" bson:"fees_total"`
	// @inject_tag: json:"fees_total_local" bson:"fees_total_local"
	FeesTotalLocal *OrderViewMoney `protobuf:"bytes,27,opt,name=fees_total_local,json=feesTotalLocal,proto3" json:"fees_total_local" bson:"fees_total_local"`
	// @inject_tag: json:"net_revenue" bson:"net_revenue"
	NetRevenue *OrderViewMoney `protobuf:"bytes,28,opt,name=net_revenue,json=netRevenue,proto3" json:"net_revenue" bson:"net_revenue"`
	// @inject_tag: json:"refund_gross_revenue" bson:"refund_gross_revenue"
	RefundGrossRevenue *OrderViewMoney `protobuf:"bytes,29,opt,name=refund_gross_revenue,json=refundGrossRevenue,proto3" json:"refund_gross_revenue" bson:"refund_gross_revenue"`
	// @inject_tag: json:"method_refund_fee_tariff" bson:"method_refund_fee_tariff"
	MethodRefundFeeTariff *OrderViewMoney `protobuf:"bytes,30,opt,name=method_refund_fee_tariff,json=methodRefundFeeTariff,proto3" json:"method_refund_fee_tariff" bson:"method_refund_fee_tariff"`
	// @inject_tag: json:"merchant_refund_fixed_fee_tariff" bson:"merchant_refund_fixed_fee_tariff"
	MerchantRefundFixedFeeTariff *OrderViewMoney `protobuf:"bytes,31,opt,name=merchant_refund_fixed_fee_tariff,json=merchantRefundFixedFeeTariff,proto3" json:"merchant_refund_fixed_fee_tariff" bson:"merchant_refund_fixed_fee_tariff"`
	// @inject_tag: json:"refund_tax_fee" bson:"refund_tax_fee"
	RefundTaxFee *OrderViewMoney `protobuf:"bytes,32,opt,name=refund_tax_fee,json=refundTaxFee,proto3" json:"refund_tax_fee" bson:"refund_tax_fee"`
	// @inject_tag: json:"refund_tax_fee_currency_exchange_fee" bson:"refund_tax_fee_currency_exchange_fee"
	RefundTaxFeeCurrencyExchangeFee *OrderViewMoney `protobuf:"bytes,33,opt,name=refund_tax_fee_currency_exchange_fee,json=refundTaxFeeCurrencyExchangeFee,proto3" json:"refund_tax_fee_currency_exchange_fee" bson:"refund_tax_fee_currency_exchange_fee"`
	// @inject_tag: json:"paysuper_refund_tax_fee_currency_exchange_fee" bson:"paysuper_refund_tax_fee_currency_exchange_fee"
	PaysuperRefundTaxFeeCurrencyExchangeFee *OrderViewMoney `protobuf:"bytes,34,opt,name=paysuper_refund_tax_fee_currency_exchange_fee,json=paysuperRefundTaxFeeCurrencyExchangeFee,proto3" json:"paysuper_refund_tax_fee_currency_exchange_fee" bson:"paysuper_refund_tax_fee_currency_exchange_fee"`
	// @inject_tag: json:"refund_reverse_revenue" bson:"refund_reverse_revenue"
	RefundReverseRevenue *OrderViewMoney `protobuf:"bytes,35,opt,name=refund_reverse_revenue,json=refundReverseRevenue,proto3" json:"refund_reverse_revenue" bson:"refund_reverse_revenue"`
	// @inject_tag: json:"refund_fees_total" bson:"refund_fees_total"
	RefundFeesTotal *OrderViewMoney `protobuf:"bytes,36,opt,name=refund_fees_total,json=refundFeesTotal,proto3" json:"refund_fees_total" bson:"refund_fees_total"`
	// @inject_tag: json:"refund_fees_total_local" bson:"refund_fees_total_local"
	RefundFeesTotalLocal *OrderViewMoney `protobuf:"bytes,37,opt,name=refund_fees_total_local,json=refundFeesTotalLocal,proto3" json:"refund_fees_total_local" bson:"refund_fees_total_local"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte          `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32           `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *OrderViewPublic) Reset()         { *m = OrderViewPublic{} }
func (m *OrderViewPublic) String() string { return proto.CompactTextString(m) }
func (*OrderViewPublic) ProtoMessage()    {}
func (*OrderViewPublic) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{14}
}

func (m *OrderViewPublic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderViewPublic.Unmarshal(m, b)
}
func (m *OrderViewPublic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderViewPublic.Marshal(b, m, deterministic)
}
func (m *OrderViewPublic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderViewPublic.Merge(m, src)
}
func (m *OrderViewPublic) XXX_Size() int {
	return xxx_messageInfo_OrderViewPublic.Size(m)
}
func (m *OrderViewPublic) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderViewPublic.DiscardUnknown(m)
}

var xxx_messageInfo_OrderViewPublic proto.InternalMessageInfo

func (m *OrderViewPublic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderViewPublic) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OrderViewPublic) GetTotalPaymentAmount() float64 {
	if m != nil {
		return m.TotalPaymentAmount
	}
	return 0
}

func (m *OrderViewPublic) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *OrderViewPublic) GetProject() *ProjectOrder {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *OrderViewPublic) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *OrderViewPublic) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *OrderViewPublic) GetPaymentMethod() *PaymentMethodOrder {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *OrderViewPublic) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *OrderViewPublic) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *OrderViewPublic) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *OrderViewPublic) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderViewPublic) GetTransactionDate() *timestamp.Timestamp {
	if m != nil {
		return m.TransactionDate
	}
	return nil
}

func (m *OrderViewPublic) GetUser() *OrderUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *OrderViewPublic) GetBillingAddress() *OrderBillingAddress {
	if m != nil {
		return m.BillingAddress
	}
	return nil
}

func (m *OrderViewPublic) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OrderViewPublic) GetIsVatDeduction() bool {
	if m != nil {
		return m.IsVatDeduction
	}
	return false
}

func (m *OrderViewPublic) GetGrossRevenue() *OrderViewMoney {
	if m != nil {
		return m.GrossRevenue
	}
	return nil
}

func (m *OrderViewPublic) GetTaxFee() *OrderViewMoney {
	if m != nil {
		return m.TaxFee
	}
	return nil
}

func (m *OrderViewPublic) GetTaxFeeCurrencyExchangeFee() *OrderViewMoney {
	if m != nil {
		return m.TaxFeeCurrencyExchangeFee
	}
	return nil
}

func (m *OrderViewPublic) GetTaxFeeTotal() *OrderViewMoney {
	if m != nil {
		return m.TaxFeeTotal
	}
	return nil
}

func (m *OrderViewPublic) GetMethodFeeTotal() *OrderViewMoney {
	if m != nil {
		return m.MethodFeeTotal
	}
	return nil
}

func (m *OrderViewPublic) GetMethodFeeTariff() *OrderViewMoney {
	if m != nil {
		return m.MethodFeeTariff
	}
	return nil
}

func (m *OrderViewPublic) GetMethodFixedFeeTariff() *OrderViewMoney {
	if m != nil {
		return m.MethodFixedFeeTariff
	}
	return nil
}

func (m *OrderViewPublic) GetPaysuperFixedFee() *OrderViewMoney {
	if m != nil {
		return m.PaysuperFixedFee
	}
	return nil
}

func (m *OrderViewPublic) GetFeesTotal() *OrderViewMoney {
	if m != nil {
		return m.FeesTotal
	}
	return nil
}

func (m *OrderViewPublic) GetFeesTotalLocal() *OrderViewMoney {
	if m != nil {
		return m.FeesTotalLocal
	}
	return nil
}

func (m *OrderViewPublic) GetNetRevenue() *OrderViewMoney {
	if m != nil {
		return m.NetRevenue
	}
	return nil
}

func (m *OrderViewPublic) GetRefundGrossRevenue() *OrderViewMoney {
	if m != nil {
		return m.RefundGrossRevenue
	}
	return nil
}

func (m *OrderViewPublic) GetMethodRefundFeeTariff() *OrderViewMoney {
	if m != nil {
		return m.MethodRefundFeeTariff
	}
	return nil
}

func (m *OrderViewPublic) GetMerchantRefundFixedFeeTariff() *OrderViewMoney {
	if m != nil {
		return m.MerchantRefundFixedFeeTariff
	}
	return nil
}

func (m *OrderViewPublic) GetRefundTaxFee() *OrderViewMoney {
	if m != nil {
		return m.RefundTaxFee
	}
	return nil
}

func (m *OrderViewPublic) GetRefundTaxFeeCurrencyExchangeFee() *OrderViewMoney {
	if m != nil {
		return m.RefundTaxFeeCurrencyExchangeFee
	}
	return nil
}

func (m *OrderViewPublic) GetPaysuperRefundTaxFeeCurrencyExchangeFee() *OrderViewMoney {
	if m != nil {
		return m.PaysuperRefundTaxFeeCurrencyExchangeFee
	}
	return nil
}

func (m *OrderViewPublic) GetRefundReverseRevenue() *OrderViewMoney {
	if m != nil {
		return m.RefundReverseRevenue
	}
	return nil
}

func (m *OrderViewPublic) GetRefundFeesTotal() *OrderViewMoney {
	if m != nil {
		return m.RefundFeesTotal
	}
	return nil
}

func (m *OrderViewPublic) GetRefundFeesTotalLocal() *OrderViewMoney {
	if m != nil {
		return m.RefundFeesTotalLocal
	}
	return nil
}

type OrderViewMoney struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *OrderViewMoney) Reset()         { *m = OrderViewMoney{} }
func (m *OrderViewMoney) String() string { return proto.CompactTextString(m) }
func (*OrderViewMoney) ProtoMessage()    {}
func (*OrderViewMoney) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{15}
}

func (m *OrderViewMoney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderViewMoney.Unmarshal(m, b)
}
func (m *OrderViewMoney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderViewMoney.Marshal(b, m, deterministic)
}
func (m *OrderViewMoney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderViewMoney.Merge(m, src)
}
func (m *OrderViewMoney) XXX_Size() int {
	return xxx_messageInfo_OrderViewMoney.Size(m)
}
func (m *OrderViewMoney) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderViewMoney.DiscardUnknown(m)
}

var xxx_messageInfo_OrderViewMoney proto.InternalMessageInfo

func (m *OrderViewMoney) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderViewMoney) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type OrderBillingAddress struct {
	// @inject_tag: validate:"omitempty,alpha,len=2"
	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty" validate:"omitempty,alpha,len=2"`
	City    string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	// @inject_tag: bson:"postal_code"
	PostalCode           string   `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty" bson:"postal_code"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *OrderBillingAddress) Reset()         { *m = OrderBillingAddress{} }
func (m *OrderBillingAddress) String() string { return proto.CompactTextString(m) }
func (*OrderBillingAddress) ProtoMessage()    {}
func (*OrderBillingAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{16}
}

func (m *OrderBillingAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBillingAddress.Unmarshal(m, b)
}
func (m *OrderBillingAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBillingAddress.Marshal(b, m, deterministic)
}
func (m *OrderBillingAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBillingAddress.Merge(m, src)
}
func (m *OrderBillingAddress) XXX_Size() int {
	return xxx_messageInfo_OrderBillingAddress.Size(m)
}
func (m *OrderBillingAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBillingAddress.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBillingAddress proto.InternalMessageInfo

func (m *OrderBillingAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *OrderBillingAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OrderBillingAddress) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *OrderBillingAddress) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type OrderUser struct {
	// @inject_tag: json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"object"
	Object string `protobuf:"bytes,2,opt,name=object,proto3" json:"object"`
	// @inject_tag: json:"external_id" bson:"external_id"
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id" bson:"external_id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"email" validate:"omitempty,email"
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email" validate:"omitempty,email"`
	// @inject_tag: json:"email_verified" bson:"email_verified"
	EmailVerified bool `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified" bson:"email_verified"`
	// @inject_tag: json:"phone" validate:"omitempty,phone"
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone" validate:"omitempty,phone"`
	// @inject_tag: json:"phone_verified" bson:"phone_verified"
	PhoneVerified bool `protobuf:"varint,8,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified" bson:"phone_verified"`
	// @inject_tag: json:"ip" validate:"omitempty,ip"
	Ip string `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip" validate:"omitempty,ip"`
	// @inject_tag: json:"locale" validate:"omitempty,alpha,len=2"
	Locale string `protobuf:"bytes,10,opt,name=locale,proto3" json:"locale" validate:"omitempty,alpha,len=2"`
	// @inject_tag: json:"address"
	Address *OrderBillingAddress `protobuf:"bytes,11,opt,name=address,proto3" json:"address"`
	// @inject_tag: json:"metadata"
	Metadata map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// @inject_tag: json:"-"
	TechEmail string `protobuf:"bytes,13,opt,name=tech_email,json=techEmail,proto3" json:"-"`
	//@inject_tag: json:"notify_new_region" bson:"notify_new_region"
	NotifyNewRegion bool `protobuf:"varint,14,opt,name=notify_new_region,json=notifyNewRegion,proto3" json:"notify_new_region" bson:"notify_new_region"`
	//@inject_tag: json:"notify_new_region_email" bson:"notify_new_region_email"
	NotifyNewRegionEmail string   `protobuf:"bytes,15,opt,name=notify_new_region_email,json=notifyNewRegionEmail,proto3" json:"notify_new_region_email" bson:"notify_new_region_email"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *OrderUser) Reset()         { *m = OrderUser{} }
func (m *OrderUser) String() string { return proto.CompactTextString(m) }
func (*OrderUser) ProtoMessage()    {}
func (*OrderUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{17}
}

func (m *OrderUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderUser.Unmarshal(m, b)
}
func (m *OrderUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderUser.Marshal(b, m, deterministic)
}
func (m *OrderUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderUser.Merge(m, src)
}
func (m *OrderUser) XXX_Size() int {
	return xxx_messageInfo_OrderUser.Size(m)
}
func (m *OrderUser) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderUser.DiscardUnknown(m)
}

var xxx_messageInfo_OrderUser proto.InternalMessageInfo

func (m *OrderUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderUser) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *OrderUser) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *OrderUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *OrderUser) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *OrderUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *OrderUser) GetPhoneVerified() bool {
	if m != nil {
		return m.PhoneVerified
	}
	return false
}

func (m *OrderUser) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *OrderUser) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *OrderUser) GetAddress() *OrderBillingAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OrderUser) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OrderUser) GetTechEmail() string {
	if m != nil {
		return m.TechEmail
	}
	return ""
}

func (m *OrderUser) GetNotifyNewRegion() bool {
	if m != nil {
		return m.NotifyNewRegion
	}
	return false
}

func (m *OrderUser) GetNotifyNewRegionEmail() string {
	if m != nil {
		return m.NotifyNewRegionEmail
	}
	return ""
}

type ProjectOrder struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId           string            `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name                 map[string]string `protobuf:"bytes,3,rep,name=name,proto3" json:"name,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UrlSuccess           string            `protobuf:"bytes,4,opt,name=url_success,json=urlSuccess,proto3" json:"url_success,omitempty"`
	UrlFail              string            `protobuf:"bytes,5,opt,name=url_fail,json=urlFail,proto3" json:"url_fail,omitempty"`
	NotifyEmails         []string          `protobuf:"bytes,6,rep,name=notify_emails,json=notifyEmails,proto3" json:"notify_emails,omitempty"`
	SecretKey            string            `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SendNotifyEmail      bool              `protobuf:"varint,8,opt,name=send_notify_email,json=sendNotifyEmail,proto3" json:"send_notify_email,omitempty"`
	UrlCheckAccount      string            `protobuf:"bytes,9,opt,name=url_check_account,json=urlCheckAccount,proto3" json:"url_check_account,omitempty"`
	UrlProcessPayment    string            `protobuf:"bytes,10,opt,name=url_process_payment,json=urlProcessPayment,proto3" json:"url_process_payment,omitempty"`
	CallbackProtocol     string            `protobuf:"bytes,11,opt,name=callback_protocol,json=callbackProtocol,proto3" json:"callback_protocol,omitempty"`
	UrlChargebackPayment string            `protobuf:"bytes,12,opt,name=url_chargeback_payment,json=urlChargebackPayment,proto3" json:"url_chargeback_payment,omitempty"`
	UrlCancelPayment     string            `protobuf:"bytes,13,opt,name=url_cancel_payment,json=urlCancelPayment,proto3" json:"url_cancel_payment,omitempty"`
	UrlFraudPayment      string            `protobuf:"bytes,14,opt,name=url_fraud_payment,json=urlFraudPayment,proto3" json:"url_fraud_payment,omitempty"`
	UrlRefundPayment     string            `protobuf:"bytes,15,opt,name=url_refund_payment,json=urlRefundPayment,proto3" json:"url_refund_payment,omitempty"`
	Status               int32             `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ProjectOrder) Reset()         { *m = ProjectOrder{} }
func (m *ProjectOrder) String() string { return proto.CompactTextString(m) }
func (*ProjectOrder) ProtoMessage()    {}
func (*ProjectOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{18}
}

func (m *ProjectOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectOrder.Unmarshal(m, b)
}
func (m *ProjectOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectOrder.Marshal(b, m, deterministic)
}
func (m *ProjectOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectOrder.Merge(m, src)
}
func (m *ProjectOrder) XXX_Size() int {
	return xxx_messageInfo_ProjectOrder.Size(m)
}
func (m *ProjectOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectOrder proto.InternalMessageInfo

func (m *ProjectOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectOrder) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ProjectOrder) GetName() map[string]string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ProjectOrder) GetUrlSuccess() string {
	if m != nil {
		return m.UrlSuccess
	}
	return ""
}

func (m *ProjectOrder) GetUrlFail() string {
	if m != nil {
		return m.UrlFail
	}
	return ""
}

func (m *ProjectOrder) GetNotifyEmails() []string {
	if m != nil {
		return m.NotifyEmails
	}
	return nil
}

func (m *ProjectOrder) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ProjectOrder) GetSendNotifyEmail() bool {
	if m != nil {
		return m.SendNotifyEmail
	}
	return false
}

func (m *ProjectOrder) GetUrlCheckAccount() string {
	if m != nil {
		return m.UrlCheckAccount
	}
	return ""
}

func (m *ProjectOrder) GetUrlProcessPayment() string {
	if m != nil {
		return m.UrlProcessPayment
	}
	return ""
}

func (m *ProjectOrder) GetCallbackProtocol() string {
	if m != nil {
		return m.CallbackProtocol
	}
	return ""
}

func (m *ProjectOrder) GetUrlChargebackPayment() string {
	if m != nil {
		return m.UrlChargebackPayment
	}
	return ""
}

func (m *ProjectOrder) GetUrlCancelPayment() string {
	if m != nil {
		return m.UrlCancelPayment
	}
	return ""
}

func (m *ProjectOrder) GetUrlFraudPayment() string {
	if m != nil {
		return m.UrlFraudPayment
	}
	return ""
}

func (m *ProjectOrder) GetUrlRefundPayment() string {
	if m != nil {
		return m.UrlRefundPayment
	}
	return ""
}

func (m *ProjectOrder) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PaymentMethodOrder struct {
	// @inject_tag: json:"-" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"-" bson:"_id"`
	// @inject_tag: json:"title" bson:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"title" bson:"name"`
	// @inject_tag: bson:"external_id" json:"external_id"
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id" bson:"external_id"`
	// @inject_tag: bson:"params"
	Params *PaymentMethodParams `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty" bson:"params"`
	// @inject_tag: bson:"payment_system_id" json:"payment_system_id"
	PaymentSystemId string `protobuf:"bytes,5,opt,name=payment_system_id,json=paymentSystemId,proto3" json:"payment_system_id" bson:"payment_system_id"`
	// @inject_tag: json:"type" bson:"group_alias"
	Group string `protobuf:"bytes,6,opt,name=group,proto3" json:"type" bson:"group_alias"`
	// @inject_tag: json:"saved" bson:"saved"
	Saved bool `protobuf:"varint,7,opt,name=saved,proto3" json:"saved" bson:"saved"`
	//@inject_tag: json:"card" bson:"card"
	Card *PaymentMethodCard `protobuf:"bytes,8,opt,name=card,proto3" json:"card" bson:"card"`
	//@inject_tag: json:"wallet" bson:"wallet"
	Wallet *PaymentMethodWallet `protobuf:"bytes,9,opt,name=wallet,proto3" json:"wallet" bson:"wallet"`
	//@inject_tag: json:"crypto_currency" bson:"crypto_currency"
	CryptoCurrency *PaymentMethodCrypto `protobuf:"bytes,10,opt,name=crypto_currency,json=cryptoCurrency,proto3" json:"crypto_currency" bson:"crypto_currency"`
	// @inject_tag: json:"type" bson:"group_alias"
	Handler              string   `protobuf:"bytes,11,opt,name=handler,proto3" json:"type" bson:"group_alias"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentMethodOrder) Reset()         { *m = PaymentMethodOrder{} }
func (m *PaymentMethodOrder) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodOrder) ProtoMessage()    {}
func (*PaymentMethodOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{19}
}

func (m *PaymentMethodOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodOrder.Unmarshal(m, b)
}
func (m *PaymentMethodOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodOrder.Marshal(b, m, deterministic)
}
func (m *PaymentMethodOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodOrder.Merge(m, src)
}
func (m *PaymentMethodOrder) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodOrder.Size(m)
}
func (m *PaymentMethodOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodOrder proto.InternalMessageInfo

func (m *PaymentMethodOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethodOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentMethodOrder) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *PaymentMethodOrder) GetParams() *PaymentMethodParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PaymentMethodOrder) GetPaymentSystemId() string {
	if m != nil {
		return m.PaymentSystemId
	}
	return ""
}

func (m *PaymentMethodOrder) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *PaymentMethodOrder) GetSaved() bool {
	if m != nil {
		return m.Saved
	}
	return false
}

func (m *PaymentMethodOrder) GetCard() *PaymentMethodCard {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *PaymentMethodOrder) GetWallet() *PaymentMethodWallet {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func (m *PaymentMethodOrder) GetCryptoCurrency() *PaymentMethodCrypto {
	if m != nil {
		return m.CryptoCurrency
	}
	return nil
}

func (m *PaymentMethodOrder) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

type PaymentMethodParams struct {
	// @inject_tag: bson:"currency" json:"currency" validate:"required,alpha,len=3"
	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency" bson:"currency" validate:"required,alpha,len=3"`
	// @inject_tag: bson:"terminal_id" json:"terminal_id" validate:"omitempty,alphanum"
	TerminalId string `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id" bson:"terminal_id" validate:"omitempty,alphanum"`
	// @inject_tag: bson:"secret" json:"secret" validate:"omitempty"
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret" bson:"secret" validate:"omitempty"`
	// @inject_tag: bson:"secret_callback" json:"secret_callback" validate:"omitempty"
	SecretCallback       string   `protobuf:"bytes,5,opt,name=secret_callback,json=secretCallback,proto3" json:"secret_callback" bson:"secret_callback" validate:"omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentMethodParams) Reset()         { *m = PaymentMethodParams{} }
func (m *PaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodParams) ProtoMessage()    {}
func (*PaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{20}
}

func (m *PaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodParams.Unmarshal(m, b)
}
func (m *PaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodParams.Marshal(b, m, deterministic)
}
func (m *PaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodParams.Merge(m, src)
}
func (m *PaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodParams.Size(m)
}
func (m *PaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodParams proto.InternalMessageInfo

func (m *PaymentMethodParams) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PaymentMethodParams) GetTerminalId() string {
	if m != nil {
		return m.TerminalId
	}
	return ""
}

func (m *PaymentMethodParams) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *PaymentMethodParams) GetSecretCallback() string {
	if m != nil {
		return m.SecretCallback
	}
	return ""
}

type PaymentMethodCard struct {
	//@inject_tag: json:"first6" bson:"first6"
	First6 string `protobuf:"bytes,1,opt,name=first6,proto3" json:"first6" bson:"first6"`
	//@inject_tag: json:"last4" bson:"last4"
	Last4 string `protobuf:"bytes,2,opt,name=last4,proto3" json:"last4" bson:"last4"`
	//@inject_tag: json:"masked" bson:"masked"
	Masked string `protobuf:"bytes,3,opt,name=masked,proto3" json:"masked" bson:"masked"`
	//@inject_tag: json:"expiry_month" bson:"expiry_month"
	ExpiryMonth string `protobuf:"bytes,4,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month" bson:"expiry_month"`
	//@inject_tag: json:"expiry_year" bson:"expiry_year"
	ExpiryYear string `protobuf:"bytes,5,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year" bson:"expiry_year"`
	//@inject_tag: json:"brand" bson:"brand"
	Brand string `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand" bson:"brand"`
	//@inject_tag: json:"fingerprint" bson:"fingerprint"
	Fingerprint string `protobuf:"bytes,7,opt,name=fingerprint,proto3" json:"fingerprint" bson:"fingerprint"`
	//@inject_tag: json:"secure3d" bson:"secure3d"
	Secure3D             bool     `protobuf:"varint,8,opt,name=secure3d,proto3" json:"secure3d" bson:"secure3d"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentMethodCard) Reset()         { *m = PaymentMethodCard{} }
func (m *PaymentMethodCard) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodCard) ProtoMessage()    {}
func (*PaymentMethodCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{21}
}

func (m *PaymentMethodCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodCard.Unmarshal(m, b)
}
func (m *PaymentMethodCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodCard.Marshal(b, m, deterministic)
}
func (m *PaymentMethodCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodCard.Merge(m, src)
}
func (m *PaymentMethodCard) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodCard.Size(m)
}
func (m *PaymentMethodCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodCard.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodCard proto.InternalMessageInfo

func (m *PaymentMethodCard) GetFirst6() string {
	if m != nil {
		return m.First6
	}
	return ""
}

func (m *PaymentMethodCard) GetLast4() string {
	if m != nil {
		return m.Last4
	}
	return ""
}

func (m *PaymentMethodCard) GetMasked() string {
	if m != nil {
		return m.Masked
	}
	return ""
}

func (m *PaymentMethodCard) GetExpiryMonth() string {
	if m != nil {
		return m.ExpiryMonth
	}
	return ""
}

func (m *PaymentMethodCard) GetExpiryYear() string {
	if m != nil {
		return m.ExpiryYear
	}
	return ""
}

func (m *PaymentMethodCard) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *PaymentMethodCard) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *PaymentMethodCard) GetSecure3D() bool {
	if m != nil {
		return m.Secure3D
	}
	return false
}

type PaymentMethodWallet struct {
	//@inject_tag: json:"brand" bson:"brand"
	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand" bson:"brand"`
	//@inject_tag: json:"account" bson:"account"
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account" bson:"account"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentMethodWallet) Reset()         { *m = PaymentMethodWallet{} }
func (m *PaymentMethodWallet) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodWallet) ProtoMessage()    {}
func (*PaymentMethodWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{22}
}

func (m *PaymentMethodWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodWallet.Unmarshal(m, b)
}
func (m *PaymentMethodWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodWallet.Marshal(b, m, deterministic)
}
func (m *PaymentMethodWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodWallet.Merge(m, src)
}
func (m *PaymentMethodWallet) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodWallet.Size(m)
}
func (m *PaymentMethodWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodWallet.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodWallet proto.InternalMessageInfo

func (m *PaymentMethodWallet) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *PaymentMethodWallet) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type PaymentMethodCrypto struct {
	//@inject_tag: json:"brand" bson:"brand"
	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand" bson:"brand"`
	//@inject_tag: json:"address" bson:"address"
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address" bson:"address"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentMethodCrypto) Reset()         { *m = PaymentMethodCrypto{} }
func (m *PaymentMethodCrypto) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodCrypto) ProtoMessage()    {}
func (*PaymentMethodCrypto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{23}
}

func (m *PaymentMethodCrypto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodCrypto.Unmarshal(m, b)
}
func (m *PaymentMethodCrypto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodCrypto.Marshal(b, m, deterministic)
}
func (m *PaymentMethodCrypto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodCrypto.Merge(m, src)
}
func (m *PaymentMethodCrypto) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodCrypto.Size(m)
}
func (m *PaymentMethodCrypto) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodCrypto.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodCrypto proto.InternalMessageInfo

func (m *PaymentMethodCrypto) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *PaymentMethodCrypto) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type VatReport struct {
	//@inject_tag: json:"id" bson:"_id" validate:"omitempty,hexadecimal,len=24"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id" validate:"omitempty,hexadecimal,len=24"`
	//@inject_tag: json:"country" bson:"country" validate:"required,alpha,len=2"
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country" bson:"country" validate:"required,alpha,len=2"`
	// @inject_tag: json:"vat_rate" bson:"vat_rate" validate:"numeric,gte=0,lte=1"
	VatRate float64 `protobuf:"fixed64,3,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate" bson:"vat_rate" validate:"numeric,gte=0,lte=1"`
	//@inject_tag: json:"currency" bson:"currency" validate:"required,alpha,len=3"
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency" bson:"currency" validate:"required,alpha,len=3"`
	// @inject_tag: json:"transactions_count" bson:"transactions_count" validate:"numeric,gte=0"
	TransactionsCount int32 `protobuf:"varint,5,opt,name=transactions_count,json=transactionsCount,proto3" json:"transactions_count" bson:"transactions_count" validate:"numeric,gte=0"`
	// @inject_tag: json:"gross_revenue" bson:"gross_revenue" validate:"numeric,gte=0"
	GrossRevenue float64 `protobuf:"fixed64,6,opt,name=gross_revenue,json=grossRevenue,proto3" json:"gross_revenue" bson:"gross_revenue" validate:"numeric,gte=0"`
	// @inject_tag: json:"vat_amount" bson:"vat_amount" validate:"numeric,gte=0"
	VatAmount float64 `protobuf:"fixed64,7,opt,name=vat_amount,json=vatAmount,proto3" json:"vat_amount" bson:"vat_amount" validate:"numeric,gte=0"`
	// @inject_tag: json:"fees_amount" bson:"fees_amount" validate:"numeric,gte=0"
	FeesAmount float64 `protobuf:"fixed64,8,opt,name=fees_amount,json=feesAmount,proto3" json:"fees_amount" bson:"fees_amount" validate:"numeric,gte=0"`
	// @inject_tag: json:"deduction_amount" bson:"deduction_amount" validate:"numeric,gte=0"
	DeductionAmount float64 `protobuf:"fixed64,9,opt,name=deduction_amount,json=deductionAmount,proto3" json:"deduction_amount" bson:"deduction_amount" validate:"numeric,gte=0"`
	// @inject_tag: json:"correction_amount" bson:"correction_amount" validate:"numeric,lte=0"
	CorrectionAmount float64 `protobuf:"fixed64,10,opt,name=correction_amount,json=correctionAmount,proto3" json:"correction_amount" bson:"correction_amount" validate:"numeric,lte=0"`
	//@inject_tag: json:"status" bson:"status" validate:"required,alpha,oneof=threshold expired pending need_to_pay paid overdue canceled"
	Status string `protobuf:"bytes,11,opt,name=status,proto3" json:"status" bson:"status" validate:"required,alpha,oneof=threshold expired pending need_to_pay paid overdue canceled"`
	// @inject_tag: json:"country_annual_turnover" bson:"country_annual_turnover" validate:"numeric,gte=0"
	CountryAnnualTurnover float64 `protobuf:"fixed64,12,opt,name=country_annual_turnover,json=countryAnnualTurnover,proto3" json:"country_annual_turnover" bson:"country_annual_turnover" validate:"numeric,gte=0"`
	// @inject_tag: json:"world_annual_turnover" bson:"world_annual_turnover" validate:"numeric,gte=0"
	WorldAnnualTurnover float64 `protobuf:"fixed64,13,opt,name=world_annual_turnover,json=worldAnnualTurnover,proto3" json:"world_annual_turnover" bson:"world_annual_turnover" validate:"numeric,gte=0"`
	//@inject_tag: json:"amounts_approximate" bson:"amounts_approximate"
	AmountsApproximate bool `protobuf:"varint,14,opt,name=amounts_approximate,json=amountsApproximate,proto3" json:"amounts_approximate" bson:"amounts_approximate"`
	//@inject_tag: json:"date_from" bson:"date_from"
	DateFrom *timestamp.Timestamp `protobuf:"bytes,15,opt,name=date_from,json=dateFrom,proto3" json:"date_from" bson:"date_from"`
	//@inject_tag: json:"date_to" bson:"date_to"
	DateTo *timestamp.Timestamp `protobuf:"bytes,16,opt,name=date_to,json=dateTo,proto3" json:"date_to" bson:"date_to"`
	//@inject_tag: json:"pay_until_date" bson:"pay_until_date"
	PayUntilDate *timestamp.Timestamp `protobuf:"bytes,17,opt,name=pay_until_date,json=payUntilDate,proto3" json:"pay_until_date" bson:"pay_until_date"`
	//@inject_tag: json:"created_at" bson:"created_at"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at" bson:"created_at"`
	//@inject_tag: json:"updated_at" bson:"updated_at"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" bson:"updated_at"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *VatReport) Reset()         { *m = VatReport{} }
func (m *VatReport) String() string { return proto.CompactTextString(m) }
func (*VatReport) ProtoMessage()    {}
func (*VatReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{24}
}

func (m *VatReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VatReport.Unmarshal(m, b)
}
func (m *VatReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VatReport.Marshal(b, m, deterministic)
}
func (m *VatReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VatReport.Merge(m, src)
}
func (m *VatReport) XXX_Size() int {
	return xxx_messageInfo_VatReport.Size(m)
}
func (m *VatReport) XXX_DiscardUnknown() {
	xxx_messageInfo_VatReport.DiscardUnknown(m)
}

var xxx_messageInfo_VatReport proto.InternalMessageInfo

func (m *VatReport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VatReport) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *VatReport) GetVatRate() float64 {
	if m != nil {
		return m.VatRate
	}
	return 0
}

func (m *VatReport) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *VatReport) GetTransactionsCount() int32 {
	if m != nil {
		return m.TransactionsCount
	}
	return 0
}

func (m *VatReport) GetGrossRevenue() float64 {
	if m != nil {
		return m.GrossRevenue
	}
	return 0
}

func (m *VatReport) GetVatAmount() float64 {
	if m != nil {
		return m.VatAmount
	}
	return 0
}

func (m *VatReport) GetFeesAmount() float64 {
	if m != nil {
		return m.FeesAmount
	}
	return 0
}

func (m *VatReport) GetDeductionAmount() float64 {
	if m != nil {
		return m.DeductionAmount
	}
	return 0
}

func (m *VatReport) GetCorrectionAmount() float64 {
	if m != nil {
		return m.CorrectionAmount
	}
	return 0
}

func (m *VatReport) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VatReport) GetCountryAnnualTurnover() float64 {
	if m != nil {
		return m.CountryAnnualTurnover
	}
	return 0
}

func (m *VatReport) GetWorldAnnualTurnover() float64 {
	if m != nil {
		return m.WorldAnnualTurnover
	}
	return 0
}

func (m *VatReport) GetAmountsApproximate() bool {
	if m != nil {
		return m.AmountsApproximate
	}
	return false
}

func (m *VatReport) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *VatReport) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

func (m *VatReport) GetPayUntilDate() *timestamp.Timestamp {
	if m != nil {
		return m.PayUntilDate
	}
	return nil
}

func (m *VatReport) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VatReport) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateFileResponse)(nil), "proto.CreateFileResponse")
	proto.RegisterType((*LoadFileRequest)(nil), "proto.LoadFileRequest")
	proto.RegisterType((*LoadFileResponse)(nil), "proto.LoadFileResponse")
	proto.RegisterType((*ResponseError)(nil), "proto.ResponseError")
	proto.RegisterType((*ResponseErrorMessage)(nil), "proto.ResponseErrorMessage")
	proto.RegisterType((*ReportFile)(nil), "proto.ReportFile")
	proto.RegisterType((*File)(nil), "proto.File")
	proto.RegisterType((*ReportRequest)(nil), "proto.ReportRequest")
	proto.RegisterType((*GeneratorPayload)(nil), "proto.GeneratorPayload")
	proto.RegisterType((*GeneratorTemplate)(nil), "proto.GeneratorTemplate")
	proto.RegisterType((*GeneratorOptions)(nil), "proto.GeneratorOptions")
	proto.RegisterType((*RoyaltyReportDetails)(nil), "proto.RoyaltyReportDetails")
	proto.RegisterType((*RoyaltyReportCorrection)(nil), "proto.RoyaltyReportCorrection")
	proto.RegisterType((*RoyaltyReport)(nil), "proto.RoyaltyReport")
	proto.RegisterType((*OrderViewPublic)(nil), "proto.OrderViewPublic")
	proto.RegisterType((*OrderViewMoney)(nil), "proto.OrderViewMoney")
	proto.RegisterType((*OrderBillingAddress)(nil), "proto.OrderBillingAddress")
	proto.RegisterType((*OrderUser)(nil), "proto.OrderUser")
	proto.RegisterMapType((map[string]string)(nil), "proto.OrderUser.MetadataEntry")
	proto.RegisterType((*ProjectOrder)(nil), "proto.ProjectOrder")
	proto.RegisterMapType((map[string]string)(nil), "proto.ProjectOrder.NameEntry")
	proto.RegisterType((*PaymentMethodOrder)(nil), "proto.PaymentMethodOrder")
	proto.RegisterType((*PaymentMethodParams)(nil), "proto.PaymentMethodParams")
	proto.RegisterType((*PaymentMethodCard)(nil), "proto.PaymentMethodCard")
	proto.RegisterType((*PaymentMethodWallet)(nil), "proto.PaymentMethodWallet")
	proto.RegisterType((*PaymentMethodCrypto)(nil), "proto.PaymentMethodCrypto")
	proto.RegisterType((*VatReport)(nil), "proto.VatReport")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 2740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xdb, 0x72, 0xdc, 0xc6,
	0xd1, 0xfe, 0x97, 0x87, 0x3d, 0xf4, 0x72, 0x0f, 0x1c, 0x52, 0x24, 0x44, 0x5b, 0x26, 0xbd, 0xb2,
	0xcb, 0xfa, 0x1d, 0x8b, 0x8a, 0x65, 0xd9, 0x8e, 0xed, 0x9c, 0x68, 0x4a, 0x74, 0xa9, 0x2c, 0xc9,
	0x2c, 0x98, 0x96, 0x2b, 0xa9, 0x8a, 0x51, 0x43, 0x60, 0x96, 0x44, 0x84, 0x05, 0x90, 0xc1, 0x80,
	0xe2, 0xe6, 0x11, 0x72, 0x91, 0x5c, 0xe4, 0x26, 0x2f, 0x90, 0xbc, 0x40, 0xaa, 0x72, 0x93, 0xa7,
	0xc8, 0x53, 0xa4, 0x2a, 0xb9, 0xca, 0x1b, 0xa4, 0xa6, 0x7b, 0x06, 0x0b, 0xec, 0xae, 0x96, 0x52,
	0x2a, 0xb9, 0x21, 0xd1, 0xdd, 0x5f, 0xf7, 0xcc, 0xf4, 0x74, 0xcf, 0xf4, 0xf4, 0x42, 0x3b, 0x95,
	0x89, 0x4a, 0xf6, 0xf1, 0x2f, 0x5b, 0xc5, 0x7f, 0x3b, 0xbb, 0x67, 0x49, 0x72, 0x16, 0x89, 0x3b,
	0x48, 0x9d, 0xe6, 0xc3, 0x3b, 0x2a, 0x1c, 0x89, 0x4c, 0xf1, 0x51, 0x4a, 0xb8, 0xc1, 0x6f, 0x6a,
	0xc0, 0x0e, 0xa5, 0xe0, 0x4a, 0x1c, 0x85, 0x91, 0x70, 0x45, 0x96, 0x26, 0x71, 0x26, 0xd8, 0x16,
	0xd4, 0x33, 0xc5, 0x55, 0x9e, 0x39, 0xb5, 0xbd, 0xda, 0xad, 0x55, 0xd7, 0x50, 0xec, 0x43, 0x68,
	0x8c, 0x44, 0x96, 0xf1, 0x33, 0xe1, 0x2c, 0xed, 0xd5, 0x6e, 0xb5, 0xef, 0xbe, 0x46, 0x76, 0xf6,
	0xad, 0xe6, 0x03, 0x29, 0x13, 0xf9, 0x98, 0x20, 0xae, 0xc5, 0xb2, 0xb7, 0x61, 0x65, 0x18, 0x46,
	0xc2, 0x59, 0x46, 0x9d, 0xf5, 0x42, 0x27, 0x4d, 0xa4, 0xc2, 0x71, 0x51, 0x3c, 0xf8, 0x1c, 0x7a,
	0x8f, 0x12, 0x1e, 0xd0, 0x4c, 0x7e, 0x95, 0x8b, 0x4c, 0xb1, 0x5d, 0x68, 0x8f, 0x84, 0xf4, 0xcf,
	0x79, 0xac, 0xbc, 0x30, 0xc0, 0xd9, 0xb4, 0x5c, 0xb0, 0xac, 0x87, 0x01, 0xeb, 0xc2, 0x52, 0x18,
	0xe0, 0x64, 0x5a, 0xee, 0x52, 0x18, 0x0c, 0xfe, 0x58, 0x83, 0xfe, 0xc4, 0xc8, 0xff, 0x66, 0x39,
	0xbb, 0x95, 0xe5, 0xb4, 0x8d, 0xce, 0x64, 0x21, 0xec, 0x4d, 0x58, 0xf3, 0x93, 0x58, 0x89, 0x58,
	0x79, 0x6a, 0x9c, 0x0a, 0x67, 0x05, 0xa7, 0xd7, 0x36, 0xbc, 0x93, 0x71, 0x2a, 0x06, 0xdf, 0x41,
	0xa7, 0x32, 0xc8, 0x7f, 0x79, 0x8e, 0x83, 0xef, 0x60, 0x73, 0x1e, 0x80, 0x31, 0x58, 0xf1, 0x93,
	0x40, 0x18, 0x4f, 0xe2, 0x37, 0x73, 0xaa, 0x43, 0xb4, 0x26, 0x2b, 0x75, 0xa0, 0x11, 0x08, 0xc5,
	0xc3, 0x28, 0xc3, 0xc5, 0xb6, 0x5c, 0x4b, 0x0e, 0xfe, 0x51, 0x03, 0x98, 0x6c, 0xa0, 0xd9, 0x86,
	0x9a, 0xdd, 0x86, 0xe9, 0x7d, 0x5b, 0x9a, 0xd9, 0xb7, 0x5d, 0x68, 0x4b, 0x54, 0x27, 0x0f, 0x91,
	0x75, 0x20, 0x96, 0x76, 0x10, 0x7b, 0x0d, 0x5a, 0xda, 0x97, 0x65, 0x07, 0x36, 0x35, 0x03, 0x85,
	0x5b, 0x50, 0x4f, 0xb9, 0xe4, 0xa3, 0xcc, 0x59, 0xdd, 0xab, 0xdd, 0x5a, 0x73, 0x0d, 0xc5, 0x76,
	0xa0, 0xa9, 0xc4, 0x28, 0x8d, 0xb8, 0x12, 0x4e, 0x9d, 0x74, 0x2c, 0xcd, 0x3e, 0x01, 0xf0, 0x31,
	0xd2, 0x03, 0x8f, 0x2b, 0xa7, 0x85, 0xbe, 0xdc, 0xd9, 0xa7, 0x04, 0xd9, 0xb7, 0x09, 0xb2, 0x7f,
	0x62, 0x13, 0xc4, 0x6d, 0x19, 0xf4, 0x81, 0x1a, 0xec, 0xc0, 0x0a, 0xae, 0x92, 0x99, 0x8d, 0xaf,
	0xe1, 0xa0, 0x14, 0xb4, 0x7f, 0xab, 0xe9, 0x9d, 0xd4, 0xd3, 0xb6, 0x31, 0xbb, 0x0d, 0x0d, 0x9c,
	0x79, 0xe1, 0x90, 0xba, 0x26, 0x69, 0xcd, 0x76, 0x36, 0x25, 0xa7, 0x58, 0xd6, 0xc3, 0x80, 0xdd,
	0x84, 0x4e, 0x92, 0xab, 0x34, 0x57, 0xde, 0x30, 0x91, 0x23, 0xae, 0x8c, 0x5b, 0xd6, 0x88, 0x79,
	0x84, 0x3c, 0x76, 0x03, 0x40, 0xf1, 0xd3, 0x48, 0x78, 0x31, 0x1f, 0x59, 0xcf, 0xb4, 0x90, 0xf3,
	0x84, 0x8f, 0xd0, 0x35, 0xc3, 0x50, 0x44, 0x81, 0x76, 0xcd, 0x32, 0x0d, 0xae, 0x29, 0xb6, 0x09,
	0xab, 0x23, 0xae, 0xfc, 0x73, 0xf4, 0xcb, 0x9a, 0x4b, 0x84, 0xe6, 0x9e, 0xc9, 0x24, 0x4f, 0x9d,
	0x06, 0x71, 0x91, 0x18, 0xfc, 0xae, 0x06, 0xfd, 0x2f, 0x44, 0x2c, 0x24, 0x57, 0x89, 0x3c, 0xe6,
	0xe3, 0x28, 0xe1, 0x01, 0xbb, 0x57, 0xf2, 0x6d, 0x0d, 0xbd, 0xe7, 0x98, 0x48, 0x2c, 0xa0, 0x27,
	0x46, 0x5e, 0xf2, 0xfa, 0xfb, 0xd0, 0x48, 0x52, 0x15, 0x26, 0x71, 0x66, 0xc2, 0x77, 0x7b, 0x5a,
	0xe9, 0x2b, 0x12, 0xbb, 0x16, 0xa7, 0xbd, 0x1c, 0x70, 0xc5, 0x71, 0xf1, 0x6b, 0x2e, 0x7e, 0x0f,
	0x14, 0xac, 0xcf, 0x8c, 0xc2, 0xae, 0x43, 0x33, 0x3b, 0xd7, 0x21, 0x54, 0x78, 0xba, 0x81, 0xf4,
	0xc3, 0x40, 0xdb, 0x40, 0xf7, 0x90, 0x8f, 0xf1, 0x5b, 0x7b, 0x46, 0x0a, 0x3f, 0x2c, 0xa2, 0xcd,
	0x50, 0x3a, 0xc8, 0x4d, 0x66, 0x1a, 0x6f, 0x5a, 0x72, 0xf0, 0x5e, 0xc9, 0x0d, 0x66, 0x9a, 0x1a,
	0xad, 0x0f, 0xd1, 0x24, 0x57, 0x76, 0x4c, 0x43, 0x0e, 0xfe, 0x5e, 0x83, 0x4d, 0x37, 0x19, 0xf3,
	0x48, 0x8d, 0x29, 0x20, 0xee, 0x53, 0xae, 0xe8, 0xe3, 0xe0, 0x4c, 0x26, 0x59, 0xe6, 0xf1, 0x51,
	0x92, 0xc7, 0xa4, 0x57, 0x73, 0xdb, 0xc8, 0x3b, 0x40, 0x16, 0xbb, 0x0d, 0x4c, 0x49, 0x1e, 0x67,
	0xdc, 0xc7, 0x51, 0x3c, 0x1f, 0x81, 0x4b, 0x78, 0x12, 0xac, 0x97, 0x25, 0x87, 0x08, 0xbf, 0x01,
	0x30, 0x14, 0xc2, 0xda, 0x5b, 0x46, 0x7b, 0xad, 0xa1, 0x10, 0xc6, 0xda, 0x0d, 0x80, 0x0b, 0xae,
	0xac, 0x78, 0x85, 0xc4, 0x17, 0x5c, 0x19, 0xf1, 0x4d, 0xe8, 0xa4, 0x7c, 0x9c, 0xe4, 0x05, 0x62,
	0x15, 0x11, 0x6b, 0xc4, 0x34, 0xa0, 0x1d, 0x68, 0xfa, 0xb9, 0x94, 0x22, 0xf6, 0xc7, 0x36, 0x95,
	0x2c, 0x3d, 0x78, 0x08, 0xdb, 0x95, 0x85, 0x1e, 0x26, 0x52, 0x0a, 0x9c, 0x9f, 0x76, 0x72, 0x65,
	0x95, 0x86, 0x22, 0xe7, 0xf3, 0x2c, 0x89, 0xcd, 0x96, 0x18, 0x6a, 0xf0, 0x87, 0x55, 0xe8, 0x54,
	0x6c, 0xbd, 0xfa, 0x51, 0x52, 0x4d, 0xec, 0xe5, 0x57, 0x48, 0x6c, 0xad, 0x9a, 0xa7, 0x81, 0x55,
	0x5d, 0xb9, 0x5a, 0xd5, 0xa0, 0x0f, 0x94, 0x3e, 0x9f, 0x8c, 0x13, 0xc3, 0x00, 0x1d, 0xd8, 0x72,
	0x9b, 0xc4, 0x78, 0x18, 0xb0, 0xcf, 0xa0, 0x6d, 0x84, 0x81, 0x3d, 0x8a, 0x16, 0x1b, 0x06, 0x82,
	0xdf, 0xd7, 0x61, 0x3d, 0xb9, 0x09, 0x1a, 0xe4, 0x2a, 0x73, 0x13, 0x68, 0xa3, 0x42, 0x86, 0x49,
	0xe0, 0x0d, 0x65, 0x32, 0x72, 0x9a, 0x2f, 0x61, 0x14, 0xe1, 0x47, 0x32, 0x19, 0xb1, 0x8f, 0xa1,
	0x65, 0x94, 0x55, 0xf2, 0x12, 0x87, 0x5f, 0x93, 0xc0, 0x27, 0x09, 0xbb, 0x0f, 0x7d, 0xee, 0xfb,
	0x22, 0x55, 0x9e, 0xb8, 0x4c, 0x43, 0x29, 0xb4, 0xa3, 0xe0, 0x4a, 0xfd, 0x2e, 0xe9, 0x3c, 0x40,
	0x95, 0x03, 0xa5, 0xe7, 0x4e, 0x1c, 0xf2, 0x74, 0xfb, 0xea, 0xb9, 0x5b, 0xf8, 0x81, 0xd2, 0x57,
	0x20, 0x45, 0x51, 0xe6, 0xac, 0x55, 0xaf, 0xc0, 0x39, 0xd9, 0xe6, 0x5a, 0x2c, 0xfb, 0x31, 0x80,
	0x5f, 0x04, 0xa6, 0xd3, 0x41, 0xcd, 0x37, 0xe6, 0x69, 0x4e, 0xc2, 0xd7, 0x2d, 0x69, 0x0c, 0xfe,
	0xd9, 0x87, 0xde, 0x57, 0x32, 0x10, 0xf2, 0x69, 0x28, 0x9e, 0x1f, 0xe7, 0xa7, 0x51, 0xe8, 0xcf,
	0x04, 0x27, 0x83, 0x95, 0x3c, 0x2f, 0xa2, 0x12, 0xbf, 0xd9, 0xf7, 0x61, 0x53, 0x25, 0x8a, 0x47,
	0x5e, 0xca, 0xc7, 0x23, 0x5d, 0x03, 0x54, 0xd2, 0x94, 0xa1, 0xec, 0x98, 0x44, 0x73, 0x72, 0x6d,
	0xa5, 0x9a, 0x6b, 0xec, 0x36, 0x34, 0x52, 0x99, 0xfc, 0x52, 0xf8, 0x94, 0xa6, 0xed, 0xbb, 0x1b,
	0x66, 0x09, 0xc7, 0xc4, 0xc5, 0x19, 0xba, 0x16, 0x33, 0x95, 0x0c, 0xf5, 0x57, 0x49, 0x86, 0x3d,
	0x68, 0x97, 0x4e, 0x1a, 0x13, 0x7c, 0x65, 0x16, 0xfb, 0x29, 0x74, 0xed, 0x9a, 0x46, 0x42, 0x9d,
	0x27, 0x81, 0x09, 0xc2, 0xeb, 0x76, 0x4a, 0x24, 0x7c, 0x8c, 0x32, 0x9a, 0x58, 0x27, 0x2d, 0xf3,
	0xa8, 0x32, 0xca, 0x63, 0x25, 0xc7, 0x1e, 0x96, 0x21, 0x2d, 0x5b, 0x19, 0x21, 0xef, 0x50, 0x57,
	0x23, 0x53, 0xf9, 0x0e, 0x33, 0xf9, 0xbe, 0x05, 0xf5, 0x28, 0xf1, 0x79, 0x24, 0x30, 0x8c, 0x5a,
	0xae, 0xa1, 0x4a, 0x79, 0xb3, 0x56, 0xc9, 0x9b, 0x07, 0xd0, 0x2f, 0x2d, 0x82, 0x32, 0xb2, 0x73,
	0xa5, 0x63, 0x7a, 0x25, 0x1d, 0x4c, 0xcb, 0xb7, 0x60, 0x25, 0xcf, 0x84, 0x74, 0xba, 0xa8, 0xda,
	0x37, 0x4b, 0xc6, 0x55, 0x7e, 0x93, 0x09, 0xe9, 0xa2, 0x94, 0x1d, 0x42, 0xef, 0x34, 0x8c, 0xa2,
	0x30, 0x3e, 0xf3, 0x78, 0x10, 0x48, 0x91, 0x65, 0x4e, 0xcf, 0x8c, 0x55, 0x52, 0xf8, 0x9c, 0x20,
	0x07, 0x84, 0x70, 0xbb, 0xa7, 0x15, 0x5a, 0x47, 0x15, 0x96, 0x3d, 0x7d, 0x8a, 0x2a, 0xfd, 0xcd,
	0x6e, 0x41, 0x3f, 0xcc, 0x3c, 0x7d, 0xac, 0x07, 0x22, 0xc8, 0x69, 0x8b, 0xd6, 0xf7, 0x6a, 0xb7,
	0x9a, 0x6e, 0x37, 0xcc, 0x9e, 0x72, 0x75, 0xdf, 0x72, 0xd9, 0xa7, 0xd0, 0xa1, 0xeb, 0x46, 0x8a,
	0x0b, 0x11, 0xe7, 0xc2, 0x61, 0x38, 0x81, 0x6b, 0xe5, 0x09, 0xe8, 0x90, 0x7e, 0x9c, 0xc4, 0x62,
	0xec, 0xd2, 0xd5, 0xe4, 0x12, 0x94, 0xed, 0x43, 0x43, 0xf1, 0x4b, 0x6f, 0x28, 0x84, 0xb3, 0xb1,
	0x48, 0xab, 0xae, 0xf8, 0xe5, 0x91, 0x10, 0xec, 0x5b, 0xb8, 0x61, 0xf0, 0x9e, 0x8d, 0x58, 0x4f,
	0x5c, 0xea, 0x9d, 0x3a, 0x13, 0x68, 0x65, 0x73, 0x91, 0x95, 0xeb, 0x64, 0xe5, 0xd0, 0x68, 0x3e,
	0x30, 0x8a, 0xda, 0xf0, 0x27, 0xd0, 0xb1, 0x86, 0x31, 0x61, 0x9c, 0x6b, 0x8b, 0x0c, 0xb5, 0xc9,
	0xd0, 0x89, 0x46, 0xb2, 0x9f, 0x40, 0x9f, 0xa2, 0xb3, 0xa4, 0xbd, 0xb5, 0x48, 0xbb, 0x4b, 0xf0,
	0xc2, 0xc0, 0x01, 0xac, 0x97, 0x0d, 0x70, 0x19, 0x0e, 0x87, 0xce, 0xf6, 0x22, 0x0b, 0xbd, 0x89,
	0x05, 0x44, 0xb3, 0x47, 0xb0, 0x6d, 0x4d, 0x84, 0x97, 0xa2, 0x62, 0xc8, 0x59, 0x64, 0x68, 0xd3,
	0x18, 0xd2, 0x4a, 0x13, 0x6b, 0x87, 0xc0, 0x52, 0x3e, 0xce, 0xf2, 0x54, 0xc8, 0x89, 0x3d, 0xe7,
	0xfa, 0x22, 0x43, 0x7d, 0xab, 0x60, 0x4d, 0xb1, 0x7b, 0x58, 0x33, 0x64, 0xc6, 0x21, 0x3b, 0x8b,
	0x94, 0x75, 0x29, 0x91, 0x15, 0xce, 0x9c, 0x68, 0x79, 0x98, 0x69, 0xce, 0x6b, 0x0b, 0x9d, 0x59,
	0xe8, 0x3e, 0xd2, 0x60, 0xf6, 0x11, 0xb4, 0x63, 0xa1, 0x8a, 0x58, 0x7c, 0x7d, 0x91, 0x2e, 0xc4,
	0x42, 0xd9, 0x48, 0xfc, 0x02, 0x36, 0xa5, 0x18, 0xe6, 0x71, 0xe0, 0x55, 0x83, 0xf9, 0xc6, 0x22,
	0x03, 0x8c, 0x54, 0xbe, 0x28, 0x87, 0xf4, 0x13, 0x70, 0xcc, 0x56, 0x18, 0x7b, 0xa5, 0xbd, 0x78,
	0x63, 0x91, 0xb1, 0x6b, 0xa4, 0xe6, 0xa2, 0xd6, 0x64, 0x33, 0x7e, 0x01, 0x7b, 0xc5, 0xf9, 0x64,
	0x2d, 0x4e, 0xef, 0xf1, 0xee, 0x22, 0xbb, 0xaf, 0x5b, 0x75, 0x63, 0xb9, 0xba, 0xd7, 0x9f, 0x41,
	0xd7, 0x58, 0xb5, 0x89, 0xb8, 0xb7, 0x30, 0x7d, 0x09, 0x7c, 0x42, 0xe9, 0x18, 0xc0, 0x5b, 0x55,
	0xe5, 0x17, 0x64, 0xe5, 0x9b, 0x8b, 0x4c, 0xee, 0x96, 0x4d, 0xce, 0xcb, 0xcd, 0x1c, 0x6e, 0x17,
	0xe1, 0xf8, 0x52, 0xc3, 0x0d, 0x16, 0x0d, 0xf7, 0x8e, 0xb5, 0xe5, 0x5e, 0x31, 0xec, 0x97, 0xb0,
	0x65, 0x46, 0xd3, 0xb1, 0x20, 0x33, 0x51, 0xc4, 0xc4, 0xcd, 0x85, 0x29, 0x45, 0x4a, 0x2e, 0xe9,
	0xd8, 0xa8, 0x38, 0x80, 0xf5, 0x49, 0x38, 0xd8, 0xa4, 0x78, 0x6b, 0x61, 0x8e, 0x4b, 0x1b, 0x08,
	0x26, 0x35, 0x1e, 0xc1, 0xf6, 0x8c, 0x09, 0x93, 0x21, 0x6f, 0xbf, 0xc4, 0x84, 0x8e, 0x2a, 0x79,
	0x32, 0xb8, 0x0f, 0xdd, 0x2a, 0xee, 0x85, 0xa5, 0x74, 0xb9, 0x5a, 0x58, 0x9a, 0xaa, 0xcc, 0x7f,
	0x0d, 0x1b, 0x73, 0x2e, 0x18, 0x7a, 0xe2, 0xe0, 0x15, 0x6b, 0x1f, 0x2d, 0x86, 0xc4, 0x7e, 0x40,
	0xa8, 0xac, 0x21, 0xfc, 0xd6, 0x37, 0x70, 0x9a, 0x64, 0x7a, 0x35, 0x78, 0x47, 0x9b, 0xb7, 0x39,
	0xb1, 0xf0, 0x8a, 0xde, 0x84, 0x55, 0x7d, 0xb7, 0xda, 0xd7, 0x27, 0x11, 0x83, 0xbf, 0xae, 0x40,
	0xab, 0xb8, 0x0e, 0x67, 0x2a, 0xa5, 0x2d, 0xa8, 0x27, 0xa7, 0x58, 0xc6, 0x98, 0x07, 0x00, 0x51,
	0x7a, 0x30, 0x71, 0xa9, 0x84, 0x8c, 0x79, 0xa4, 0xaf, 0x7b, 0x33, 0x98, 0x65, 0x95, 0x9e, 0x72,
	0x2b, 0xa5, 0xa7, 0xdc, 0x26, 0xac, 0x8a, 0x11, 0x0f, 0x23, 0x53, 0x78, 0x13, 0xc1, 0xde, 0x86,
	0x2e, 0x7e, 0x78, 0x17, 0x42, 0x86, 0xc3, 0x50, 0x04, 0x58, 0xff, 0x34, 0xdd, 0x0e, 0x72, 0x9f,
	0x1a, 0xa6, 0x56, 0x4e, 0xcf, 0x93, 0x58, 0x98, 0x0a, 0x87, 0x08, 0xad, 0x8c, 0x1f, 0x13, 0xe5,
	0x26, 0x29, 0x23, 0xb7, 0x50, 0xd6, 0xcb, 0x4a, 0x4d, 0xd9, 0xb2, 0x14, 0xa6, 0xa5, 0x62, 0x04,
	0x2a, 0xc5, 0xc8, 0x3d, 0x68, 0xd8, 0xfb, 0xbf, 0x7d, 0xe5, 0xfd, 0x6f, 0xa1, 0xec, 0x53, 0x68,
	0x8e, 0x84, 0xe2, 0xf8, 0xfc, 0x5d, 0xdb, 0x5b, 0x2e, 0x15, 0xac, 0x85, 0x63, 0xf7, 0x1f, 0x1b,
	0xc0, 0x03, 0xbd, 0x7f, 0x6e, 0x81, 0xc7, 0xbe, 0x80, 0xf0, 0xcf, 0x3d, 0x72, 0x4c, 0xc7, 0xf4,
	0x05, 0x84, 0x7f, 0xfe, 0x00, 0x9d, 0xf3, 0x2e, 0xac, 0xc7, 0x89, 0x0a, 0x87, 0x63, 0x2f, 0x16,
	0xcf, 0x3d, 0x29, 0xce, 0x74, 0x01, 0xd1, 0xc5, 0x25, 0xf6, 0x48, 0xf0, 0x44, 0x3c, 0x77, 0x91,
	0xcd, 0x3e, 0x84, 0xed, 0x19, 0xac, 0xb1, 0xdb, 0x43, 0xbb, 0x9b, 0x53, 0x1a, 0x38, 0xc4, 0xce,
	0x67, 0xd0, 0xa9, 0x4c, 0x8e, 0xf5, 0x61, 0xf9, 0x99, 0xb0, 0x21, 0xa7, 0x3f, 0xb5, 0xef, 0x2f,
	0x78, 0x94, 0xdb, 0x87, 0x39, 0x11, 0x9f, 0x2e, 0xfd, 0xa0, 0x36, 0xf8, 0xcb, 0x2a, 0xac, 0x95,
	0x4b, 0xda, 0x57, 0x7f, 0x07, 0xbe, 0x6f, 0x02, 0x65, 0x19, 0x1d, 0x77, 0x63, 0x4e, 0x99, 0xbc,
	0xff, 0x84, 0x8f, 0x04, 0xf9, 0x8d, 0xe2, 0x68, 0x17, 0xda, 0xb9, 0x8c, 0xbc, 0x2c, 0xf7, 0x7d,
	0xbd, 0x53, 0x14, 0x62, 0x90, 0xcb, 0xe8, 0x6b, 0xe2, 0xb0, 0xeb, 0xd0, 0xd4, 0x80, 0xe1, 0x24,
	0xd6, 0x1a, 0xb9, 0x8c, 0x8e, 0xb4, 0x43, 0x6f, 0x42, 0xc7, 0x38, 0x09, 0x3d, 0x93, 0x39, 0x75,
	0xec, 0xb7, 0xac, 0x11, 0x13, 0x3d, 0x92, 0xe9, 0x4d, 0xc9, 0x84, 0x2f, 0x85, 0xf2, 0xb4, 0x23,
	0x28, 0xe0, 0x5a, 0xc4, 0xf9, 0x52, 0x8c, 0xf5, 0xa6, 0x64, 0x22, 0x0e, 0xbc, 0xb2, 0x21, 0x13,
	0x77, 0x3d, 0x2d, 0x78, 0x32, 0xb1, 0xa5, 0xb1, 0x7a, 0x2a, 0xfe, 0xb9, 0xf0, 0x9f, 0x79, 0xdc,
	0xa7, 0x0e, 0x01, 0x05, 0x62, 0x2f, 0x97, 0xd1, 0xa1, 0xe6, 0x1f, 0x10, 0x9b, 0xed, 0xc3, 0x86,
	0xc6, 0xa6, 0x32, 0xd1, 0xab, 0xb0, 0x0f, 0x11, 0x13, 0xa2, 0xda, 0xcc, 0x31, 0x49, 0x4c, 0xc1,
	0xce, 0xbe, 0x07, 0xeb, 0x3e, 0x8f, 0xa2, 0x53, 0xee, 0x3f, 0xf3, 0xd0, 0x6d, 0x7e, 0x12, 0x99,
	0xea, 0xba, 0x6f, 0x05, 0xc7, 0x86, 0xcf, 0xee, 0xc1, 0x16, 0x4d, 0x84, 0xcb, 0x33, 0x41, 0x2a,
	0xc6, 0x3e, 0xd5, 0xdd, 0x9b, 0x38, 0x1b, 0x2b, 0xb4, 0x43, 0xbc, 0x07, 0x0c, 0xb5, 0x78, 0xec,
	0x8b, 0xe2, 0x69, 0x64, 0xc2, 0xb4, 0xaf, 0x35, 0x50, 0x60, 0xd1, 0x66, 0xb1, 0x43, 0xc9, 0xf3,
	0xa0, 0x00, 0x77, 0x8b, 0xc5, 0x1e, 0x69, 0xfe, 0x94, 0x65, 0x73, 0x16, 0x5b, 0x70, 0xaf, 0xb0,
	0x4c, 0xf7, 0x8a, 0x45, 0x4f, 0x5e, 0x09, 0xfd, 0x72, 0x9f, 0x75, 0xe7, 0x63, 0x68, 0x15, 0xd1,
	0xf1, 0x4a, 0x81, 0xfb, 0xa7, 0x65, 0x60, 0xb3, 0x0f, 0x9f, 0x79, 0x2f, 0xc5, 0x99, 0x8e, 0xd4,
	0x95, 0x67, 0xdf, 0xdd, 0xa2, 0xcf, 0xb9, 0x52, 0x39, 0x44, 0x2a, 0xe3, 0x1d, 0x23, 0xa2, 0xe8,
	0x81, 0xbe, 0x0b, 0xeb, 0xf6, 0x91, 0x96, 0x8d, 0x33, 0x25, 0x46, 0x93, 0x06, 0x45, 0xcf, 0x08,
	0xbe, 0x46, 0xfe, 0xc3, 0x60, 0xd2, 0xfe, 0xa3, 0x0e, 0x0f, 0x11, 0x78, 0xbc, 0xf3, 0x0b, 0x11,
	0x60, 0xbc, 0x36, 0x5d, 0x22, 0xd8, 0x7b, 0xb0, 0xe2, 0x73, 0x69, 0x9f, 0x7c, 0xce, 0xbc, 0x99,
	0x1c, 0x72, 0x19, 0xb8, 0x88, 0xd2, 0x33, 0x7f, 0xce, 0xa3, 0x48, 0x4c, 0x3a, 0xad, 0x73, 0xf0,
	0xdf, 0x22, 0xc2, 0x35, 0x48, 0xfd, 0x76, 0xf2, 0xe5, 0x38, 0x55, 0x49, 0x51, 0x46, 0x14, 0x9d,
	0x86, 0x79, 0x83, 0x21, 0xd4, 0xed, 0x92, 0x8a, 0x2d, 0x18, 0xf4, 0x55, 0x77, 0xce, 0xe3, 0x20,
	0x12, 0xd2, 0x04, 0xb0, 0x25, 0x07, 0xbf, 0xaf, 0xc1, 0xc6, 0x1c, 0xc7, 0x55, 0xee, 0xd3, 0xda,
	0xd4, 0xeb, 0x1b, 0x5b, 0xb6, 0x72, 0x14, 0x9a, 0x1d, 0x2a, 0x5a, 0xb6, 0xc4, 0xa2, 0xc7, 0x28,
	0xa5, 0xb3, 0x6d, 0x2a, 0x12, 0xc5, 0xde, 0x81, 0x9e, 0x49, 0x7c, 0x9b, 0x3f, 0x66, 0x0f, 0xba,
	0xc4, 0x3e, 0x34, 0xdc, 0xc1, 0xbf, 0x6a, 0xb0, 0x3e, 0xe3, 0x44, 0xea, 0xe2, 0xca, 0x4c, 0x7d,
	0x34, 0x69, 0x21, 0x6b, 0x4a, 0x6f, 0x4d, 0xc4, 0x33, 0x75, 0xcf, 0x86, 0x21, 0x12, 0x1a, 0x3d,
	0xe2, 0xd9, 0x33, 0x61, 0x43, 0xc8, 0x50, 0xfa, 0xb5, 0x8d, 0x4d, 0x9b, 0xb1, 0x37, 0x4a, 0x62,
	0x75, 0x6e, 0x7f, 0x87, 0x20, 0xde, 0x63, 0xcd, 0xa2, 0x10, 0x44, 0xc8, 0x58, 0x70, 0x69, 0xe6,
	0x08, 0xc4, 0xfa, 0x99, 0xe0, 0x52, 0x8f, 0x78, 0x2a, 0x79, 0x1c, 0xd8, 0x10, 0x41, 0x82, 0xed,
	0x41, 0x7b, 0x18, 0xc6, 0x67, 0x42, 0xa6, 0x32, 0x8c, 0x95, 0xed, 0x15, 0x94, 0x58, 0xda, 0xab,
	0x99, 0xf0, 0x73, 0x29, 0x3e, 0xb0, 0x37, 0x69, 0x41, 0x0f, 0x1e, 0x4c, 0x6d, 0x04, 0xc5, 0xc1,
	0x64, 0xa8, 0x5a, 0x79, 0x28, 0x07, 0x1a, 0xf6, 0xb4, 0x33, 0xbf, 0x4e, 0x18, 0x72, 0xc6, 0x0c,
	0x45, 0xc4, 0x02, 0x33, 0xe6, 0x42, 0xb6, 0x66, 0x88, 0x1c, 0xfc, 0xb9, 0x0e, 0xad, 0xa7, 0x5c,
	0xbd, 0xa0, 0xfd, 0x58, 0x2a, 0x9d, 0x96, 0xaa, 0xa5, 0xd3, 0x75, 0x68, 0xea, 0xe7, 0xb8, 0xd4,
	0x85, 0x10, 0xf5, 0x76, 0x1a, 0x17, 0x5c, 0xb9, 0x5c, 0x89, 0x2b, 0x1a, 0x3a, 0xf3, 0x5a, 0xbd,
	0xab, 0x2f, 0x6a, 0xf5, 0xde, 0x9c, 0x7e, 0xcd, 0xd7, 0xa9, 0x59, 0x5b, 0x79, 0xb6, 0x57, 0x1b,
	0xbe, 0x8d, 0xe9, 0x86, 0xef, 0x2e, 0xb4, 0xb1, 0x44, 0x35, 0xf2, 0x26, 0xca, 0xf1, 0x35, 0x68,
	0x00, 0xff, 0x0f, 0xfd, 0xa2, 0xab, 0x60, 0x51, 0x2d, 0x44, 0xf5, 0x0a, 0xbe, 0x81, 0xea, 0xab,
	0xa2, 0xe8, 0x91, 0x59, 0x2c, 0x20, 0xb6, 0x3f, 0x11, 0x1c, 0x14, 0x5d, 0x5f, 0x73, 0xd8, 0xb6,
	0x2b, 0x2d, 0x99, 0x8f, 0x60, 0xdb, 0xb6, 0x81, 0x78, 0x1c, 0xe7, 0x3c, 0xf2, 0x54, 0x2e, 0xe3,
	0xe4, 0x42, 0x48, 0xbc, 0x43, 0x6a, 0xee, 0x35, 0x23, 0x3e, 0x40, 0xe9, 0x89, 0x11, 0xb2, 0xbb,
	0x70, 0xed, 0x79, 0x22, 0xa3, 0x60, 0x46, 0xab, 0x83, 0x5a, 0x1b, 0x28, 0x9c, 0xd2, 0xb9, 0x03,
	0x1b, 0xa6, 0x23, 0xe8, 0xf1, 0x34, 0x95, 0xc9, 0x65, 0x38, 0xd2, 0x3b, 0x46, 0xa5, 0x0f, 0x33,
	0xa2, 0x83, 0x89, 0x84, 0x7d, 0x0c, 0xad, 0x80, 0x2b, 0x41, 0x5d, 0xd6, 0xde, 0xd5, 0xad, 0x52,
	0x0d, 0xc6, 0x1e, 0xeb, 0x07, 0xd0, 0x40, 0x45, 0x95, 0xe0, 0xdd, 0xb2, 0x58, 0xad, 0xae, 0xa1,
	0x27, 0x89, 0xe9, 0xa9, 0x79, 0x79, 0xac, 0xc2, 0x88, 0x7a, 0x53, 0xeb, 0x57, 0xea, 0xae, 0xa5,
	0x7c, 0xfc, 0x8d, 0x56, 0xb8, 0x3f, 0xfb, 0xc3, 0x16, 0xfb, 0xcf, 0xfb, 0xdf, 0x1b, 0xaf, 0xd0,
	0xff, 0xbe, 0xfb, 0xdb, 0x1a, 0xf4, 0x28, 0x65, 0x84, 0xfc, 0x5a, 0xc8, 0x8b, 0xd0, 0x17, 0xec,
	0x87, 0x00, 0x93, 0x1f, 0x93, 0xd9, 0xec, 0xef, 0xbc, 0x3b, 0xb6, 0x51, 0x38, 0xfb, 0x93, 0xf3,
	0xe0, 0xff, 0xd8, 0x8f, 0xa0, 0x69, 0x7f, 0xb9, 0x65, 0x5b, 0x06, 0x38, 0xf5, 0x7b, 0xf0, 0xce,
	0xf6, 0x0c, 0xdf, 0xaa, 0x7f, 0xfe, 0xfe, 0xcf, 0xef, 0x9c, 0x85, 0xea, 0x3c, 0x3f, 0xdd, 0xf7,
	0x93, 0xd1, 0x1d, 0xfb, 0xa8, 0x2c, 0x3e, 0x6e, 0x4b, 0x33, 0xd9, 0x3b, 0xe9, 0xb3, 0x33, 0xf3,
	0x83, 0x78, 0x1d, 0xff, 0x7d, 0xf0, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x77, 0x26, 0xab,
	0x3b, 0x1f, 0x00, 0x00,
}
