// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportRequest struct {
	//@inject_tag: json:"file_id" validate:"required,hexadecimal,len=24"
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id" validate:"required,hexadecimal,len=24"`
	//@inject_tag: json:"template_id" validate:"required,alpha"
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id" validate:"required,alpha"`
	//@inject_tag: json:"template_id" validate:"required,alpha"
	OutputFormat string `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"template_id" validate:"required,alpha"`
	//@inject_tag: json:"table_name" validate:"required,alpha"
	TableName string `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name" validate:"required,alpha"`
	//@inject_tag: json:"fields" validate:"required,dive,alpha"
	Fields []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields" validate:"required,dive,alpha"`
	//@inject_tag: json:"match" validate:"required"
	Match []byte `protobuf:"bytes,6,opt,name=match,proto3" json:"match" validate:"required"`
	//@inject_tag: json:"group"
	Group                []byte   `protobuf:"bytes,7,opt,name=group,proto3" json:"group"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *ReportRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ReportRequest) GetOutputFormat() string {
	if m != nil {
		return m.OutputFormat
	}
	return ""
}

func (m *ReportRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ReportRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ReportRequest) GetMatch() []byte {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *ReportRequest) GetGroup() []byte {
	if m != nil {
		return m.Group
	}
	return nil
}

type Payload struct {
	//@inject_tag: json:"template"
	Template *PayloadTemplate `protobuf:"bytes,1,opt,name=template,proto3" json:"template"`
	//@inject_tag: json:"options"
	Options *PayloadOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options"`
	//@inject_tag: json:"data"
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTemplate() *PayloadTemplate {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Payload) GetOptions() *PayloadOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PayloadTemplate struct {
	//@inject_tag: json:"shortid,omitempty"
	ShortId string `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"shortid,omitempty"`
	//@inject_tag: json:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//@inject_tag: json:"recipe,omitempty"
	Recipe string `protobuf:"bytes,3,opt,name=recipe,proto3" json:"recipe,omitempty"`
	//@inject_tag: json:"content,omitempty"
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PayloadTemplate) Reset()         { *m = PayloadTemplate{} }
func (m *PayloadTemplate) String() string { return proto.CompactTextString(m) }
func (*PayloadTemplate) ProtoMessage()    {}
func (*PayloadTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *PayloadTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadTemplate.Unmarshal(m, b)
}
func (m *PayloadTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadTemplate.Marshal(b, m, deterministic)
}
func (m *PayloadTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadTemplate.Merge(m, src)
}
func (m *PayloadTemplate) XXX_Size() int {
	return xxx_messageInfo_PayloadTemplate.Size(m)
}
func (m *PayloadTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadTemplate proto.InternalMessageInfo

func (m *PayloadTemplate) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

func (m *PayloadTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayloadTemplate) GetRecipe() string {
	if m != nil {
		return m.Recipe
	}
	return ""
}

func (m *PayloadTemplate) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PayloadOptions struct {
	//@inject_tag: json:"timeout,omitempty"
	Timeout              string   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PayloadOptions) Reset()         { *m = PayloadOptions{} }
func (m *PayloadOptions) String() string { return proto.CompactTextString(m) }
func (*PayloadOptions) ProtoMessage()    {}
func (*PayloadOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *PayloadOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadOptions.Unmarshal(m, b)
}
func (m *PayloadOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadOptions.Marshal(b, m, deterministic)
}
func (m *PayloadOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadOptions.Merge(m, src)
}
func (m *PayloadOptions) XXX_Size() int {
	return xxx_messageInfo_PayloadOptions.Size(m)
}
func (m *PayloadOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadOptions proto.InternalMessageInfo

func (m *PayloadOptions) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type File struct {
	//@inject_tag: json:"file,omitempty"
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*ReportRequest)(nil), "pkg.ReportRequest")
	proto.RegisterType((*Payload)(nil), "pkg.Payload")
	proto.RegisterType((*PayloadTemplate)(nil), "pkg.PayloadTemplate")
	proto.RegisterType((*PayloadOptions)(nil), "pkg.PayloadOptions")
	proto.RegisterType((*File)(nil), "pkg.File")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x68, 0x9b, 0xb4, 0x93, 0x14, 0x24, 0x53, 0x41, 0x40, 0x42, 0x54, 0xe1, 0x52, 0x40,
	0x0d, 0xa8, 0xbc, 0x01, 0x87, 0x4a, 0xbd, 0x00, 0xb2, 0x38, 0xed, 0xa5, 0x72, 0x13, 0x37, 0xb5,
	0x9a, 0xc4, 0x5e, 0x67, 0x72, 0xe8, 0x65, 0xdf, 0x71, 0xdf, 0x68, 0xe5, 0x49, 0xd2, 0xfd, 0xb9,
	0x44, 0xf3, 0xfd, 0xc4, 0xe3, 0xf9, 0x3c, 0x10, 0x1a, 0xab, 0x51, 0xa7, 0xf4, 0x65, 0x23, 0x73,
	0x2e, 0x92, 0x7b, 0x0f, 0xe6, 0x5c, 0x1a, 0x6d, 0x91, 0xcb, 0xdb, 0x56, 0x36, 0xc8, 0xde, 0x43,
	0x70, 0x54, 0xa5, 0xdc, 0xab, 0x3c, 0xf6, 0x96, 0xde, 0x6a, 0xc6, 0x7d, 0x07, 0x77, 0x39, 0xfb,
	0x0c, 0x21, 0xca, 0xca, 0x94, 0x02, 0x49, 0x7c, 0x45, 0x22, 0x0c, 0xd4, 0x2e, 0x67, 0x5f, 0x60,
	0xae, 0x5b, 0x34, 0x2d, 0xee, 0x8f, 0xda, 0x56, 0x02, 0xe3, 0x11, 0x59, 0xa2, 0x8e, 0xdc, 0x12,
	0xc7, 0x3e, 0x01, 0xa0, 0x38, 0x94, 0x72, 0x5f, 0x8b, 0x4a, 0xc6, 0x63, 0x72, 0xcc, 0x88, 0xf9,
	0x23, 0x2a, 0xc9, 0xde, 0x81, 0x7f, 0x54, 0xb2, 0xcc, 0x9b, 0x78, 0xb2, 0x1c, 0x75, 0xcd, 0x1d,
	0x62, 0x0b, 0x98, 0x54, 0x02, 0xb3, 0x53, 0xec, 0x2f, 0xbd, 0x55, 0xc4, 0x3b, 0xe0, 0xd8, 0xc2,
	0xea, 0xd6, 0xc4, 0x41, 0xc7, 0x12, 0x48, 0xee, 0x20, 0xf8, 0x27, 0x2e, 0xa5, 0x16, 0x39, 0xfb,
	0x09, 0xd3, 0xe1, 0x82, 0x34, 0x4d, 0xb8, 0x59, 0xa4, 0xe6, 0x5c, 0xa4, 0xbd, 0xfe, 0xbf, 0xd7,
	0xf8, 0xd5, 0xc5, 0xd6, 0x10, 0x68, 0x83, 0x4a, 0xd7, 0x0d, 0x4d, 0x18, 0x6e, 0xde, 0x3e, 0xfd,
	0xe1, 0x6f, 0x27, 0xf1, 0xc1, 0xc3, 0x18, 0x8c, 0x73, 0x81, 0x82, 0x46, 0x8d, 0x38, 0xd5, 0x89,
	0x85, 0x37, 0x2f, 0xce, 0x67, 0x1f, 0x60, 0xda, 0x9c, 0xb4, 0xc5, 0xc7, 0x54, 0x03, 0xc2, 0xbb,
	0xdc, 0x9d, 0x40, 0x51, 0x74, 0x79, 0x52, 0xed, 0x52, 0xb0, 0x32, 0x53, 0x46, 0xf6, 0x11, 0xf6,
	0x88, 0xc5, 0x10, 0x64, 0xba, 0x46, 0x59, 0x63, 0x9f, 0xdc, 0x00, 0x93, 0x6f, 0xf0, 0xfa, 0xf9,
	0x15, 0x9d, 0x17, 0x55, 0x25, 0x75, 0x8b, 0x43, 0xc7, 0x1e, 0x26, 0x1f, 0x61, 0xbc, 0x55, 0xa5,
	0x74, 0x9d, 0xdd, 0xd3, 0x92, 0x1c, 0x71, 0xaa, 0x7f, 0x7f, 0xbf, 0xf9, 0x5a, 0x28, 0x3c, 0xb5,
	0x87, 0x34, 0xd3, 0xd5, 0x0f, 0x23, 0x2e, 0x4d, 0x6b, 0xa4, 0xbd, 0x16, 0x6b, 0x4b, 0xbb, 0xe2,
	0x98, 0x73, 0x71, 0xf0, 0x69, 0x91, 0x7e, 0x3d, 0x04, 0x00, 0x00, 0xff, 0xff, 0xde, 0xfd, 0x3b,
	0xa6, 0x57, 0x02, 0x00, 0x00,
}
